# Assets are inputs even when no executable needs relinking. Only this owned output directory is synchronized.
cmake_minimum_required(VERSION 3.20)
if(NOT IS_DIRECTORY "${SOURCE}" OR NOT DEFINED DESTINATION OR NOT DEFINED BUILD_ROOT)
    message(FATAL_ERROR "Missing asset source, destination or build root")
endif()
file(REAL_PATH "${BUILD_ROOT}" build_root)
file(REAL_PATH "${DESTINATION}" destination)
cmake_path(IS_PREFIX build_root "${destination}" NORMALIZE inside_build)
if(NOT inside_build OR destination STREQUAL build_root OR IS_SYMLINK "${DESTINATION}")
    message(FATAL_ERROR "Asset destination must remain inside its build directory")
endif()
file(MAKE_DIRECTORY "${destination}")
file(GLOB_RECURSE inputs LIST_DIRECTORIES FALSE RELATIVE "${SOURCE}" "${SOURCE}/*")
file(GLOB_RECURSE existing LIST_DIRECTORIES TRUE RELATIVE "${destination}" "${destination}/*")
foreach(relative IN LISTS existing)
    if(IS_SYMLINK "${destination}/${relative}")
        message(FATAL_ERROR "Refusing to modify symlink in asset output: ${relative}")
    endif()
    file(REAL_PATH "${destination}/${relative}" resolved)
    cmake_path(IS_PREFIX destination "${resolved}" NORMALIZE inside_assets)
    if(NOT inside_assets)
        message(FATAL_ERROR "Asset output escaped its owned directory")
    endif()
    if(NOT IS_DIRECTORY "${resolved}" AND NOT relative IN_LIST inputs)
        file(REMOVE "${resolved}")
    endif()
endforeach()
foreach(relative IN LISTS inputs)
    if(IS_SYMLINK "${SOURCE}/${relative}")
        message(FATAL_ERROR "Symlink asset inputs are unsupported: ${relative}")
    endif()
    get_filename_component(parent "${destination}/${relative}" DIRECTORY)
    file(MAKE_DIRECTORY "${parent}")
    configure_file("${SOURCE}/${relative}" "${destination}/${relative}" COPYONLY)
endforeach()
