#!/usr/bin/env python3
"""Build an offline API reference from a source directory's headers and comments.

Run from any directory with Python 3.10+. No external packages or description
catalog are required. Only index.html is emitted outside component/.
"""

from __future__ import annotations

import argparse
from collections import Counter, defaultdict
from dataclasses import replace
from functools import lru_cache
import hashlib
import html
import json
from pathlib import Path
import posixpath
import re
import sys
from urllib.parse import quote, unquote, urlsplit, urlunsplit

from parser import Decl, parse_header, slug

HERE = Path(__file__).resolve().parent
OUTPUT = HERE.parent
REPOSITORY = OUTPUT.parent.parent
ROOT = REPOSITORY if (REPOSITORY / "src" / "Public").is_dir() else OUTPUT.parent / "dy_engine"
HEADERS = ROOT / "src" / "Public"
MARKER = "<!-- Generated by dy_engine_docs/component/generate.py. -->"
LEGACY_MARKER = "<!-- Generated by docs/rhi/generate.py. -->"
PREVIOUS_MARKER = "<!-- Generated by docs/rhi/component/generate.py. -->"
KINDS = {"class": "클래스", "struct": "구조체", "enum": "열거형", "alias": "별칭", "function": "함수", "variable": "전역 변수", "union": "공용체", "macro": "매크로"}
NO_COMMENT = "설명 주석 없음"


def escape(value):
    return html.escape(str(value), quote=True)


def member_anchor(name):
    return "member-" + slug(name)


def related_anchor(key):
    return "function-" + slug(key)


def module_name(header):
    path = Path(header)
    parts = path.with_suffix("").parts
    if parts[0] == "dyf":
        if len(parts) > 2 and parts[1] == "Extends":
            return "확장: " + parts[2]
        if len(parts) > 1 and parts[1] in {"RHI", "Math", "Platform"}:
            return parts[1]
        return "dyf"
    return path.parent.as_posix() if path.parent != Path(".") else "기본"


def public_members(decl, prefix=""):
    """Promote anonymous aggregate fields and retain named nested type scopes."""
    for member in decl.members:
        # A friend function is not a member callable as Class::Function. Keep
        # its friend declaration in the class synopsis; namespace declarations
        # have their own API entries and search targets.
        if member.kind == "function":
            continue
        anonymous = bool(re.fullmatch(r"anonymous-(?:struct|union|enum)-\d+", member.name))
        name = prefix + member.name
        if not anonymous:
            yield replace(member, name=name)
        if member.members:
            yield from public_members(member, prefix if anonymous else name + "::")


@lru_cache(maxsize=16384)
def relative_url(target, directory):
    # The same navigation links occur on every API page. Resolve each distinct
    # target once per output directory when generating a large source tree.
    parsed = urlsplit(html.unescape(target))
    if not parsed.path or parsed.scheme or parsed.netloc:
        return target
    path = posixpath.relpath(unquote(parsed.path), directory)
    return escape(urlunsplit(("", "", quote(path, safe="/"), parsed.query, parsed.fragment)))


def relative_links(document, filename):
    """Resolve site-root paths relative to each page, including file: browsing."""
    directory = posixpath.dirname(filename) or "."
    return re.sub(r'(href|src)="([^"]*)"',
                  lambda match: f'{match.group(1)}="{relative_url(match.group(2), directory)}"', document)


class Reference:
    def __init__(self, headers=None):
        self.headers = Path(headers if headers is not None else ROOT / "src" / "Public").resolve()
        self.project_name = ROOT.name
        try:
            self.source_label = self.headers.relative_to(ROOT).as_posix()
        except ValueError:
            self.source_label = self.headers.name
        self.sources = {
            path.relative_to(self.headers).as_posix(): path.read_text(encoding="utf-8")
            for path in sorted(self.headers.rglob("*"))
            if path.is_file() and path.suffix.lower() in (".h", ".hpp", ".hh", ".hxx")
        }
        if not self.sources:
            raise ValueError(f"No headers found in {self.headers}")
        self.diagnostics = []
        parsed = [decl for name, source in self.sources.items()
                  for decl in parse_header(self.headers / name, source, header=name, diagnostics=self.diagnostics)]
        if not parsed and not self.diagnostics:
            raise ValueError(f"No API declarations found in {self.headers}; check the headers and supported syntax")
        self.namespaces = sorted({decl.namespace for decl in parsed})
        grouped = defaultdict(list)
        for decl in parsed:
            # Public and internal include roots may define different APIs with
            # the same qualified name. Keep each header's declarations distinct.
            identity = (decl.namespace, decl.name, decl.header)
            grouped[identity].append(decl)
        occurrences = Counter((namespace, name) for namespace, name, _ in grouped)
        self.symbols = {}
        self.overloads = {}
        self.members = {}
        self.symbol_urls = {}
        occupied = {}
        for (namespace, name, header), declarations in grouped.items():
            if len(declarations) > 1:
                if any(decl.kind not in ("function", "macro", "alias", "variable") for decl in declarations):
                    raise ValueError(f"Duplicate symbol: {namespace}::{name}")
                # Separate preprocessor branches may repeat the same no-op macro.
                identities = {(decl.syntax, decl.condition if decl.kind == "macro" else "") for decl in declarations}
                if len(identities) != len(declarations):
                    raise ValueError(f"Duplicate function declaration: {namespace}::{name}")
            key = f"{namespace}::{name}" if namespace and len(self.namespaces) > 1 else name
            if occurrences[(namespace, name)] > 1 or name.startswith("operator"):
                key = f"{Path(header).with_suffix('').as_posix()}-{key}"
            url = "component/api-" + slug(key) + ".html"
            if url in occupied:
                raise ValueError(f"Page slug collision: {occupied[url]} and {key} -> {url}")
            occupied[url] = key
            self.symbols[key] = declarations[0]
            self.overloads[key] = declarations
            self.members[key] = list(public_members(declarations[0]))
            self.symbol_urls[key] = url
            anchors = {}
            for member in self.members[key]:
                anchor = member_anchor(member.name)
                if anchor in anchors and anchors[anchor] != member.name:
                    raise ValueError(f"Member anchor collision: {key}::{anchors[anchor]} and {member.name}")
                anchors[anchor] = member.name
        self.header_urls = {}
        for name in self.sources:
            url = f"component/header-{slug(Path(name).with_suffix('').as_posix())}.html"
            if url in occupied:
                raise ValueError(f"Header page slug collision: {occupied[url]} and {name}")
            occupied[url] = name
            self.header_urls[name] = url
        self.by_header = {name: [] for name in self.sources}
        for key, declaration in self.symbols.items():
            self.by_header[declaration.header].append((key, declaration))
        modules = {module_name(header) for header in self.sources}
        preferred = {name: index for index, name in enumerate(("dyf", "RHI", "Math", "Platform", "확장: Model"))}
        self.by_module = {name: [] for name in sorted(modules, key=lambda name: (preferred.get(name, len(preferred)), name))}
        self.module_headers = {name: [] for name in self.by_module}
        for header, values in self.by_header.items():
            module = module_name(header)
            self.by_module[module].extend(values)
            self.module_headers[module].append(header)
        self.function_owners = {}
        self.related_functions = {}
        self.api_pages = dict(self.symbols)
        self.api_groups = {module: {"API": [key for key, _ in values]}
                           for module, values in self.by_module.items()}
        self.pages = {}
        self.current = ""
        self.editorial = {}
        self.guides = []
        self.authored_hashes = {}
        if self.headers == (ROOT / "src" / "Public").resolve():
            owners_path = HERE / "api_owners.json"
            if owners_path.is_file():
                self.load_api_owners(owners_path)
                self.api_groups = {module: {"API": [key for key, _ in values if key in self.api_pages]}
                                   for module, values in self.by_module.items()}
            groups_path = HERE / "api_groups.json"
            if groups_path.is_file():
                self.load_api_groups(groups_path)
            for filename in ("frontend_reference.json", "rhi_reference.json"):
                path = HERE / filename
                if path.is_file():
                    source = path.read_text(encoding="utf-8")
                    values = json.loads(source)
                    duplicates = self.editorial.keys() & values.keys()
                    if duplicates:
                        raise ValueError(f"Duplicate authored descriptions: {sorted(duplicates)}")
                    self.editorial.update(values)
                    self.authored_hashes[filename] = hashlib.sha256(source.encode("utf-8")).hexdigest()
            guide_path = HERE / "guides.json"
            if guide_path.is_file():
                source = guide_path.read_text(encoding="utf-8")
                self.guides = json.loads(source)
                self.authored_hashes[guide_path.name] = hashlib.sha256(source.encode("utf-8")).hexdigest()
            declared = {self.qualified(decl): key for key, decl in self.symbols.items()}
            for name, entry in self.editorial.items():
                if name not in declared:
                    raise ValueError(f"Authored API no longer exists: {name}")
                member_names = {m.name for m in self.members[declared[name]]}
                unknown = entry.get("members", {}).keys() - member_names
                if unknown:
                    raise ValueError(f"Authored members no longer exist: {name}: {sorted(unknown)}")

    def load_api_owners(self, path):
        source = path.read_text(encoding="utf-8")
        catalog = json.loads(source)
        if not isinstance(catalog, dict):
            raise ValueError("API owners must be a function-to-type mapping")
        for key, targets in catalog.items():
            if key not in self.symbols or self.symbols[key].kind != "function":
                raise ValueError(f"Unknown function in API owners: {key}")
            owners = [targets] if isinstance(targets, str) else targets
            if (not isinstance(owners, list) or not owners
                    or any(not isinstance(owner, str) for owner in owners)
                    or len(set(owners)) != len(owners)):
                raise ValueError(f"Invalid API owners: {key}")
            for owner in owners:
                if owner not in self.symbols or self.symbols[owner].kind not in {"class", "struct", "enum", "alias", "union"}:
                    raise ValueError(f"Unknown type in API owners: {key}: {owner}")
            assigned = {owner: [] for owner in owners}
            for decl in self.overloads[key]:
                matches = owners if isinstance(targets, str) else [owner for owner in owners
                    if re.search(r"(?<![\w:])(?:" + re.escape(self.symbols[owner].namespace) + r"::)?"
                                 + re.escape(self.symbols[owner].name) + r"\b", decl.syntax)]
                if len(matches) != 1:
                    raise ValueError(f"Function overload needs exactly one owner: {key}: {decl.syntax}")
                assigned[matches[0]].append(decl)
            for owner, declarations in assigned.items():
                if not declarations:
                    raise ValueError(f"API owner has no overloads: {key}: {owner}")
                self.related_functions.setdefault(owner, {})[key] = declarations
            self.function_owners[key] = owners
            self.symbol_urls[key] = self.related_url(owners[0], key)
        self.api_pages = {key: decl for key, decl in self.symbols.items() if key not in self.function_owners}
        self.authored_hashes[path.name] = hashlib.sha256(source.encode("utf-8")).hexdigest()

    def load_api_groups(self, path):
        source = path.read_text(encoding="utf-8")
        groups = json.loads(source)
        if not isinstance(groups, dict) or groups.keys() != self.by_module.keys():
            raise ValueError("API groups must contain exactly the current modules")
        seen = set()
        for module, categories in groups.items():
            if not isinstance(categories, dict) or not categories:
                raise ValueError(f"API module has no categories: {module}")
            allowed = {key for key, _ in self.by_module[module]}
            for category, keys in categories.items():
                if not category.strip() or not isinstance(keys, list) or not keys:
                    raise ValueError(f"Invalid API category: {module}: {category}")
                for key in keys:
                    if not isinstance(key, str) or key not in self.api_pages:
                        raise ValueError(f"Unknown API in groups: {key}")
                    if key in seen:
                        raise ValueError(f"Duplicate API in groups: {key}")
                    if key not in allowed:
                        raise ValueError(f"API belongs to another module: {module}: {key}")
                    seen.add(key)
        missing = self.api_pages.keys() - seen
        if missing:
            raise ValueError(f"APIs missing from groups: {sorted(missing)}")
        self.api_groups = groups
        self.authored_hashes[path.name] = hashlib.sha256(source.encode("utf-8")).hexdigest()

    def qualified(self, decl):
        return f"{decl.namespace}::{decl.name}" if decl.namespace else decl.name

    def description(self, decl):
        return self.editorial.get(self.qualified(decl), {})

    def member_description(self, parent, member):
        return self.description(parent).get("members", {}).get(member.name, {})

    def field_description(self, parent, member):
        entry = self.member_description(parent, member)
        content = self.condition_note(member) + self.rich(entry.get("summary") or member.comment or NO_COMMENT)
        for remark in entry.get("remarks", []):
            content += '<p>' + self.rich(remark) + '</p>'
        if entry.get("returns"):
            content += '<p><strong>반환값:</strong> ' + self.rich(entry["returns"]) + '</p>'
        if member.comment and entry:
            content += '<p class="field-comment"><strong>헤더 주석:</strong> ' + self.rich(member.comment) + '</p>'
        return content

    def authored_content(self, entry):
        content = ""
        if entry.get("summary"):
            content += '<p>' + self.rich(entry["summary"]) + '</p>'
        if entry.get("parameters"):
            content += '<h3>매개 변수</h3>' + self.table(["이름", "설명"], [[self.rich(a), self.rich(b)] for a, b in entry["parameters"]])
        if entry.get("returns"):
            content += '<h3>반환값</h3><p>' + self.rich(entry["returns"]) + '</p>'
        if entry.get("remarks"):
            content += '<h3>설명 및 사용 규칙</h3>' + ''.join('<p>' + self.rich(p) + '</p>' for p in entry["remarks"])
        if entry.get("example"):
            content += '<h3>예제</h3>' + self.code(entry["example"])
        return content

    def summary(self, decl):
        return self.description(decl).get("summary") or (" ".join(decl.comment.split()) if decl.comment else NO_COMMENT)

    def condition_note(self, decl):
        condition = getattr(decl, "condition", "")
        return f'<p class="api-condition">조건: <code>{escape(condition)}</code></p>' if condition else ""

    def url(self, key):
        return self.symbol_urls[key]

    def related_url(self, owner, key):
        return self.url(owner) + "#" + related_anchor(key)

    def module_anchor(self, module):
        return "module-" + re.sub(r"[^\w-]+", "-", module.lower()).strip("-")

    def source_link(self, header, line=1):
        if not self.sources[header]:
            return self.header_urls[header] + "#source"
        return self.header_urls[header] + f"#L{line}"

    def diagnostics_content(self, header=None):
        entries = [entry for entry in self.diagnostics if header is None or entry["header"] == header]
        if not entries:
            return ""
        content = '<div class="notice"><strong>원문 확인이 필요한 선언</strong><p>아래 선언은 자동 분류하지 못했습니다. 해당 헤더의 원문과 함께 확인하세요.</p>'
        for entry in entries:
            content += f'<p><a href="{self.source_link(entry["header"], entry["line"])}">{escape(entry["header"])}:{entry["line"]}</a> · {escape(entry["reason"])}</p>'
            content += self.code(entry["syntax"])
        return content + '</div>'

    def link(self, key, label=None):
        if key in self.function_owners and len(self.function_owners[key]) > 1:
            return " · ".join(f'<a href="{self.related_url(owner, key)}"><code>{escape(label or self.symbols[key].name)}</code> ({escape(self.symbols[owner].name)})</a>'
                              for owner in self.function_owners[key])
        return f'<a href="{self.url(key)}"><code>{escape(label or self.symbols[key].name)}</code></a>'

    def rich(self, value):
        if re.search(r'\[[^\]]+\]\(api:[^)]+\)', value):
            parts = re.split(r'(\[[^\]]+\]\(api:[^)]+\))', value)
            output = []
            for part in parts:
                match = re.fullmatch(r'\[([^\]]+)\]\(api:([^)]+)\)', part)
                if not match:
                    output.append(self.rich(part))
                    continue
                label, name = match.groups()
                key = next((key for key, decl in self.symbols.items() if self.qualified(decl) == name), None)
                if key is None:
                    raise ValueError(f"Unknown API link in authored content: {name}")
                output.append(f'<a href="{self.url(key)}">{escape(label)}</a>')
            return ''.join(output)
        # Header text is escaped first; only explicit backticks become inline code.
        return "".join('<code>' + escape(part[1:-1]) + '</code>' if part.startswith("`") and part.endswith("`")
                       else escape(part).replace("\n", "<br>") for part in re.split(r"(`[^`]+`)", value))

    def code(self, source):
        # Keep source whitespace (including string literals) intact in the DOM
        # without introducing trailing whitespace into generated HTML files.
        escaped = re.sub(r"[ \t]+$", lambda match: "".join("&#32;" if char == " " else "&#9;" for char in match.group()),
                         escape(source), flags=re.MULTILINE)
        return '<div class="code-block"><div class="code-bar"><span>C++</span><button class="copy-button" type="button">복사</button></div><pre><code class="language-cpp">' + escaped + '</code></pre></div>'

    def table(self, headings, rows):
        return '<div class="table-scroll"><table><thead><tr>' + "".join(f'<th scope="col">{escape(h)}</th>' for h in headings) + '</tr></thead><tbody>' + "".join('<tr>' + "".join(f'<td>{cell}</td>' for cell in row) + '</tr>' for row in rows) + '</tbody></table></div>'

    def sidebar(self):
        result = '<p class="nav-heading">API 문서</p>'
        for url, title in [("index.html", "개요"), ("component/api-index.html", "API 찾아보기")]:
            current = self.current == url
            result += f'<a class="nav-link{" current" if current else ""}" href="{url}"' + (' aria-current="page"' if current else '') + f'>{title}</a>'
        for guide in self.guides:
            url = f'component/{guide["slug"]}.html'
            current = self.current == url
            result += f'<a class="nav-link{" current" if current else ""}" href="{url}"' + (' aria-current="page"' if current else '') + f'>{escape(guide["title"])}</a>'
        result += '<div class="nav-divider"></div><p class="nav-heading">모듈별 API</p>'
        for module, values in self.by_module.items():
            values = [(key, decl) for key, decl in values if key in self.api_pages]
            current = any(self.current == self.header_urls[header] for header in self.module_headers[module]) or any(self.url(key) == self.current for key, _ in values)
            result += f'<details class="nav-group" data-group="{escape(module)}"' + (' open' if current else '') + f'><summary><a href="component/api-index.html#{self.module_anchor(module)}">{escape(module)}</a><span>{len(values)}</span></summary>'
            for category, keys in self.api_groups[module].items():
                if not keys:
                    continue
                active = any(self.current == self.url(key) for key in keys)
                result += f'<details class="nav-subgroup" data-module="{escape(module)}" data-category="{escape(category)}"' + (' open' if active else '') + f'><summary>{escape(category)}<span>{len(keys)}</span></summary>'
                for key in keys:
                    decl = self.symbols[key]
                    selected = self.current == self.url(key)
                    icon = {"class": "C", "struct": "S", "enum": "E", "alias": "T", "function": "F", "variable": "V", "union": "U", "macro": "M"}[decl.kind]
                    result += f'<a class="nav-symbol{" current" if selected else ""}" href="{self.url(key)}"' + (' aria-current="page"' if selected else '') + f'><span class="type-icon {decl.kind}" aria-label="{KINDS[decl.kind]}">{icon}</span>{escape(decl.name)}</a>'
                result += '</details>'
            result += '</details>'
        return result

    def page(self, filename, title, description, content, toc, category="문서", meta=None):
        self.current = filename
        if meta is None:
            meta = escape(self.source_label) + f" · {len(self.namespaces)}개 선언 범위"
        toc_html = "".join(f'<a href="#{anchor}">{escape(label)}</a>' for anchor, label in toc)
        crumb = f'<a href="index.html">문서</a><span>/</span><a href="component/api-index.html">API 목록</a><span>/</span><span>{escape(category)}</span>'
        document = f'''<!doctype html>
{MARKER}
<html lang="ko">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="description" content="{escape(description)}">
<meta name="color-scheme" content="light dark">
<title>{escape(title)} | {escape(self.project_name)} API 문서</title>
<script src="component/assets/theme.js"></script>
<link rel="stylesheet" href="component/assets/docs.css">
<script src="component/assets/search-index.js?v={self.search_version}" defer></script>
<script src="component/assets/docs.js" defer></script>
</head>
<body data-doc-root="{'.' if filename == 'index.html' else '..'}">
<a class="skip-link" href="#main">본문으로 건너뛰기</a>
<header class="site-header">
  <a class="brand" href="index.html" aria-label="{escape(self.project_name)} 문서 홈"><span class="brand-mark" aria-hidden="true">dy</span><span>{escape(self.project_name)}</span></a>
  <span class="brand-divider"></span><a class="docs-brand" href="index.html">Docs</a>
  <div class="header-actions"><button class="search-trigger" type="button" aria-haspopup="dialog"><svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="10.5" cy="10.5" r="6.5"/><path d="m16 16 5 5"/></svg><span>문서 검색</span><kbd>/</kbd></button><button class="theme-toggle icon-button" type="button" aria-label="어두운 테마로 전환" title="테마 전환"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M20.8 14.2A9 9 0 0 1 9.8 3.2 9 9 0 1 0 20.8 14.2Z"/></svg></button></div>
</header>
<div class="product-bar"><div><button class="menu-toggle" type="button" aria-controls="sidebar" aria-expanded="false">☰ <span>목차</span></button><span class="product-title">Source API Reference</span><span class="product-tag">C++ API</span><span class="product-version">헤더 선언 기준</span></div></div>
<div class="doc-layout">
<aside class="sidebar" id="sidebar" aria-label="문서 탐색"><div class="sidebar-inner"><button class="sidebar-search search-trigger" type="button" aria-haspopup="dialog"><span>API 이름으로 검색</span><kbd>/</kbd></button><nav aria-label="API 목차">{self.sidebar()}</nav><div class="sidebar-footer"><span class="status-dot"></span>로컬에서 읽는 API 레퍼런스</div></div></aside>
<button class="nav-backdrop" type="button" aria-label="목차 닫기" hidden></button>
<main id="main" tabindex="-1"><div class="breadcrumbs" aria-label="현재 위치">{crumb}</div><div class="article-topline"><span class="eyebrow">API REFERENCE</span><button class="print-button" type="button">인쇄</button></div><h1>{escape(title)}</h1><div class="article-meta">{meta}</div><p class="lead">{self.rich(description)}</p><nav class="mobile-toc" aria-label="이 문서의 내용"><details><summary>이 문서의 내용</summary>{toc_html}</details></nav>{content}<footer class="article-footer"><p>{escape(self.project_name)} · API 문서</p><span>소스: {escape(self.source_label)} · 한국어</span><a href="#main">맨 위로 ↑</a></footer></main>
<aside class="page-toc" aria-label="이 문서의 내용"><div><h2>이 문서의 내용</h2><nav>{toc_html}</nav><div class="toc-note"><span>C++</span><p>공개 선언과<br>헤더 주석에서 생성.</p></div></div></aside>
</div>
<dialog id="search-dialog" aria-labelledby="search-title"><div class="search-heading"><h2 id="search-title">API 문서 검색</h2><button type="button" class="close-search" aria-label="검색 닫기">닫기 <kbd>Esc</kbd></button></div><label class="search-field"><svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="10.5" cy="10.5" r="6.5"/><path d="m16 16 5 5"/></svg><input id="search-input" type="search" placeholder="API, 멤버 또는 설명 검색…" autocomplete="off" spellcheck="false" aria-label="검색어" aria-controls="search-results"></label><p id="search-status" role="status" aria-live="polite"></p><div id="search-results"></div><div class="search-footer"><span>↑ ↓ 결과 이동 · Enter 열기</span><span>전체 헤더 API에서 검색</span></div></dialog>
<div class="toast" role="status" aria-live="polite"></div>
<noscript><div class="noscript-note">검색과 테마 전환에는 JavaScript가 필요합니다. 문서와 모든 API 링크는 그대로 이용할 수 있습니다.</div></noscript>
</body></html>
'''
        self.pages[filename] = relative_links(document, filename)

    def symbol_content(self, key, decl):
        content = '<section id="syntax"><h2>구문</h2>' + "".join(self.condition_note(d) + self.code(d.syntax) for d in self.overloads[key]) + '</section>'
        toc = [("syntax", "구문"), ("description", "헤더 주석")]
        entry = self.description(decl)
        if entry:
            toc.insert(1, ("usage", "사용법"))
            content += '<section id="usage"><h2>사용법</h2>' + self.authored_content(entry) + '</section>'
        content += '<section id="description"><h2>헤더 주석</h2>'
        for overload in self.overloads[key]:
            if len(self.overloads[key]) > 1:
                content += self.condition_note(overload) + self.code(overload.syntax)
            content += '<p>' + self.rich(overload.comment or NO_COMMENT) + '</p>'
            content += f'<a class="source-link" href="{self.source_link(overload.header, overload.line)}">선언 위치: {escape(overload.header)}:{overload.line} ↗</a>'
        content += '</section>'
        fields = [member for member in self.members[key] if member.kind in ("field", "value")]
        methods = [member for member in self.members[key] if member.kind == "method"]
        types = [member for member in self.members[key] if member.kind in ("class", "struct", "enum", "union", "alias")]
        if fields:
            toc.append(("fields", "열거형 값" if decl.kind == "enum" else "멤버 변수"))
            rows = []
            field_names = set()
            for member in fields:
                value = member.value if member.kind == "value" else member.syntax
                anchor = f' id="{member_anchor(member.name)}"' if member.name not in field_names else ""
                field_names.add(member.name)
                rows.append([f'<code{anchor}>{escape(member.name)}</code>',
                             f'<code>{escape(value)}</code>', self.field_description(decl, member),
                             f'<a href="{self.source_link(member.header, member.line)}">{member.line}행</a>'])
            content += f'<section id="fields"><h2>{toc[-1][1]}</h2>' + self.table(["이름", "값" if decl.kind == "enum" else "선언과 기본값", "설명", "소스"], rows) + '</section>'
        if methods:
            toc.append(("methods", "멤버 함수"))
            names = list(dict.fromkeys(member.name for member in methods))
            rows = [[f'<a href="#{member_anchor(name)}"><code>{escape(name)}</code></a>',
                     self.rich(entry.get("members", {}).get(name, {}).get("summary") or self.summary(next(member for member in methods if member.name == name)))] for name in names]
            content += '<section id="methods"><h2>멤버 함수</h2>' + self.table(["이름", "헤더 주석"], rows) + '</section>'
            for name in names:
                anchor = member_anchor(name)
                toc.append((anchor, name))
                content += f'<section class="member-detail" id="{anchor}"><h2><code>{escape(decl.name)}::{escape(name)}</code><a class="anchor-link" href="#{anchor}" aria-label="이 멤버 링크">#</a></h2>'
                for member in (m for m in methods if m.name == name):
                    content += self.condition_note(member) + self.code(member.syntax) + '<p>' + self.rich(member.comment or NO_COMMENT) + '</p>'
                    content += f'<a class="source-link" href="{self.source_link(member.header, member.line)}">선언 위치: {escape(member.header)}:{member.line} ↗</a>'
                content += self.authored_content(entry.get("members", {}).get(name, {}))
                content += '</section>'
        if types:
            for member in types:
                anchor = member_anchor(member.name)
                toc.append((anchor, member.name))
                content += f'<section id="{anchor}"><h2><code>{escape(decl.name)}::{escape(member.name)}</code> {KINDS[member.kind]}</h2>'
                content += self.condition_note(member) + self.code(member.syntax) + '<p>' + self.rich(member.comment or NO_COMMENT) + '</p>'
                content += f'<a class="source-link" href="{self.source_link(member.header, member.line)}">선언 위치: {escape(member.header)}:{member.line} ↗</a></section>'
        for operators, section, title in ((True, "operators", "연산자"), (False, "functions", "관련 함수")):
            functions = [(function, declarations) for function, declarations in self.related_functions.get(key, {}).items()
                         if self.symbols[function].name.startswith("operator") == operators]
            if not functions:
                continue
            toc.append((section, title))
            rows = [[f'<a href="#{related_anchor(function)}"><code>{escape(self.symbols[function].name)}</code></a>',
                     self.rich(self.summary(declarations[0]))] for function, declarations in functions]
            content += f'<section id="{section}"><h2>{title}</h2>' + self.table(["이름", "설명"], rows) + '</section>'
            for function, declarations in functions:
                anchor = related_anchor(function)
                name = declarations[0].name
                toc.append((anchor, name))
                content += f'<section class="member-detail" id="{anchor}"><h2><code>{escape(self.qualified(declarations[0]))}</code><a class="anchor-link" href="#{anchor}" aria-label="이 함수 링크">#</a></h2>'
                for overload in declarations:
                    if module_name(overload.header) != module_name(decl.header):
                        content += f'<p class="api-condition">{escape(module_name(overload.header))} 모듈에서 제공</p>'
                    content += self.condition_note(overload) + self.code(overload.syntax) + '<p>' + self.rich(overload.comment or NO_COMMENT) + '</p>'
                    content += f'<a class="source-link" href="{self.source_link(overload.header, overload.line)}">선언 위치: {escape(overload.header)}:{overload.line} ↗</a>'
                content += self.authored_content(self.description(declarations[0]))
                other_owners = [owner for owner in self.function_owners[function] if owner != key]
                if other_owners:
                    content += '<p>다른 타입의 오버로드: ' + ' · '.join(
                        f'<a href="{self.related_url(owner, function)}"><code>{escape(self.symbols[owner].name)}</code></a>'
                        for owner in other_owners) + '</p>'
                content += '</section>'
        toc.append(("requirements", "선언 정보"))
        content += '<section id="requirements"><h2>선언 정보</h2>' + self.table(["항목", "내용"], [
            ["헤더", f'<a href="{self.source_link(decl.header, decl.line)}"><code>{escape(decl.header)}</code></a>'],
            ["네임스페이스", f'<code>{escape(decl.namespace or "전역")}</code>'],
            ["대상 폴더 기준 경로", f'<code>{escape(decl.header)}</code>'],
        ]) + '</section>'
        if self.guides:
            guide_slugs = {guide["slug"] for guide in self.guides}
            related_slug = "rhi-lifecycle" if decl.namespace.startswith("dyf::RHI") else "model-extension" if "Extends/Model" in decl.header else "quickstart"
            if related_slug in guide_slugs:
                guide = next(guide for guide in self.guides if guide["slug"] == related_slug)
                toc.append(("related", "관련 가이드"))
                content += f'<section id="related"><h2>관련 가이드</h2><p><a href="component/{escape(related_slug)}.html">{escape(guide["title"])}</a> — {escape(guide["summary"])}</p></section>'
        return content, toc

    def symbol_page(self, key, decl):
        content, toc = self.symbol_content(key, decl)
        self.page(self.url(key), decl.name + " " + KINDS[decl.kind],
                  entry_summary if (entry_summary := self.description(decl).get("summary")) else f"{decl.namespace or '전역 범위'}에 선언된 {KINDS[decl.kind]}입니다.", content, toc, KINDS[decl.kind],
                  f'<span>{KINDS[decl.kind]}</span><span>{escape(decl.namespace or "전역")}</span><a href="{self.source_link(decl.header, decl.line)}">{escape(decl.header)}:{decl.line}</a>')

    def index_pages(self):
        counts = Counter(decl.kind for decl in self.symbols.values())
        content = '<div class="overview-actions"><a class="primary-button" href="component/api-index.html">API 찾아보기 <span>→</span></a></div>'
        if self.guides:
            content += '<section id="start"><h2>dy_engine 시작하기</h2><p>C++17 렌더링 프레임워크의 공개 API입니다. 기본 렌더러로 2D·3D 장면을 구성하거나, RHI로 GPU 자원과 명령을 직접 제어할 수 있습니다.</p><div class="guide-grid">'
            for guide in self.guides:
                content += f'<a class="guide-card" href="component/{escape(guide["slug"])}.html"><strong>{escape(guide["title"])} <span>→</span></strong><span>{escape(guide["summary"])}</span></a>'
            content += '</div></section>'
        content += '<div class="stats-strip">' + "".join(f'<div><strong>{number}</strong><span>{label}</span></div>' for number, label in [(len(self.sources), "대상 헤더"), (counts["class"], "클래스"), (counts["struct"], "구조체"), (counts["enum"], "열거형")]) + '</div>'
        content += '<section id="overview"><h2>소스 헤더에서 읽는 API</h2><p><code>' + escape(self.source_label) + '</code>의 선언, 공개 멤버, 기본값과 주석을 모았습니다. 각 항목에서 원본 헤더와 선언 위치를 확인할 수 있습니다.</p><div class="notice"><strong>설명의 출처</strong><p>설명은 헤더의 인접 주석을 그대로 표시합니다. 주석이 없는 API는 <code>설명 주석 없음</code>으로 표시됩니다. 동작과 사용 규칙은 작성된 주석과 선언을 기준으로 확인하세요.</p></div></section>'
        if self.editorial:
            content = content.replace('설명은 헤더의 인접 주석을 그대로 표시합니다. 주석이 없는 API는 <code>설명 주석 없음</code>으로 표시됩니다. 동작과 사용 규칙은 작성된 주석과 선언을 기준으로 확인하세요.', f'공개 헤더의 선언·기본값·주석을 자동으로 반영하며, {len(self.editorial)}개 주요 API에 구현과 예제를 확인한 한국어 사용법을 덧붙였습니다. 사용법과 원본 헤더 주석은 각 API 페이지에서 함께 볼 수 있습니다. 수작업 설명과 헤더 주석이 모두 없는 항목에는 선언만 제공합니다.')
        content += '<section id="browse"><h2>모듈별 API 참조</h2><p>모듈을 선택하면 API 목록과 각 항목의 구문·주석을 확인할 수 있습니다.</p><div class="related-links">'
        content += "".join(f'<a href="component/api-index.html#{self.module_anchor(module)}">{escape(module)}</a>' for module in self.by_module)
        content += '</div></section>'
        toc = [("overview", "문서 개요"), ("browse", "모듈별 API")]
        if self.guides:
            toc.insert(0, ("start", "시작 가이드"))
        self.page("index.html", "개요", "공개 선언과 헤더 주석을 함께 확인하는 API 레퍼런스입니다.", content,
                  toc)
        content = '<div class="index-filter"><label for="api-filter">API 목록 필터</label><input id="api-filter" type="search" placeholder="이름 또는 주석으로 필터…" autocomplete="off"><p id="filter-status" role="status"></p></div>'
        toc = []
        for module, values in self.by_module.items():
            anchor = self.module_anchor(module)
            toc.append((anchor, module))
            rows = [[self.link(key), KINDS[decl.kind], f'<a href="{self.source_link(decl.header, decl.line)}">{escape(decl.header)}</a>', self.rich(self.summary(decl))]
                    for key, decl in sorted(values) if key in self.api_pages]
            content += f'<section class="index-section" id="{anchor}"><h2>{escape(module)}</h2>' + self.table(["API", "종류", "헤더", "설명"], rows) + '</section>'
        self.page("component/api-index.html", "API 찾아보기", f"{len(self.api_pages)}개 API 페이지입니다. 타입별 연산자와 관련 함수는 해당 타입 페이지에서 확인할 수 있습니다.", content, toc, "API 목록")

    def header_pages(self):
        for header, source in self.sources.items():
            filename = self.header_urls[header]
            symbols = self.by_header[header]
            include = header
            content = '<section id="include"><h2>헤더 경로</h2><p>대상 폴더 기준 경로: <code>' + escape(include) + '</code></p></section>'
            content += '<section id="declarations"><h2>선언</h2>' + self.table(["이름", "종류", "헤더 주석"], [[self.link(key), KINDS[decl.kind], self.rich(self.summary(decl))] for key, decl in symbols]) + '</section>'
            content += self.diagnostics_content(header)
            content += '<section id="source"><h2>헤더 소스</h2><p>현재 대상 헤더의 사본입니다.</p><div class="source-code"><pre><code>' + "\n".join(f'<span class="source-line" id="L{i}"><a href="#L{i}" aria-label="{i}행">{i}</a>{escape(line.expandtabs(4))}</span>' for i, line in enumerate(source.splitlines(), 1)) + '</code></pre></div></section>'
            self.page(filename, f"<{include}>", f"{header}의 공개 선언과 주석을 확인합니다.", content,
                      [("include", "헤더 경로"), ("declarations", "선언"), ("source", "헤더 소스")], "헤더")

    def authored_guides(self):
        for guide in self.guides:
            content = ""
            toc = []
            for section in guide["sections"]:
                toc.append((section["id"], section["title"]))
                content += f'<section id="{escape(section["id"])}"><h2>{escape(section["title"])}</h2>'
                content += ''.join('<p>' + self.rich(p) + '</p>' for p in section.get("paragraphs", []))
                if section.get("table"):
                    table = section["table"]
                    content += self.table(table["headings"], [[self.rich(cell) for cell in row] for row in table["rows"]])
                if section.get("code"):
                    language = section.get("language", "C++")
                    block = self.code(section["code"])
                    if language not in ("C++", "cpp"):
                        block = block.replace('<span>C++</span>', '<span>' + escape(language) + '</span>').replace('class="language-cpp"', '')
                    content += block
                content += '</section>'
            example = {"quickstart": "quickstart-canvas.cpp", "rhi-lifecycle": "quickstart-rhi.cpp"}.get(guide["slug"])
            if example:
                toc.append(("example-file", "예제 파일"))
                content += f'<section id="example-file"><h2>예제 파일</h2><p><a href="component/examples/{example}" download>{example} 다운로드</a></p><p>공개 헤더를 사용하는 C++ 예제입니다. 빠른 시작의 CMake 설정으로 엔진과 연결해 빌드합니다.</p></section>'
            self.page(f'component/{guide["slug"]}.html', guide["title"], guide["summary"], content, toc, "사용 가이드")

    def build(self):
        self.pages = {}
        search = []
        for guide in self.guides:
            search.append({"title": guide["title"], "kind": "가이드", "text": guide["summary"], "url": f'component/{guide["slug"]}.html', "header": "사용 가이드"})
        for key, decl in self.symbols.items():
            if key in self.function_owners:
                for owner in self.function_owners[key]:
                    declarations = self.related_functions[owner][key]
                    search.append({"title": f"{self.qualified(decl)} ({self.symbols[owner].name})", "kind": "연산자" if decl.name.startswith("operator") else "관련 함수",
                                   "text": " · ".join(dict.fromkeys(self.summary(overload) for overload in declarations)),
                                   "url": self.related_url(owner, key), "header": decl.header})
                continue
            search_url = self.url(key)
            search.append({"title": key, "kind": KINDS[decl.kind], "text": self.summary(decl), "url": search_url, "header": decl.header})
            for name in dict.fromkeys(member.name for member in self.members[key]):
                members = [member for member in self.members[key] if member.name == name]
                text = self.description(decl).get("members", {}).get(name, {}).get("summary") or " · ".join(dict.fromkeys(self.summary(member) for member in members))
                search.append({"title": f"{key}::{name}", "kind": "멤버", "text": text,
                               "url": search_url + "#" + member_anchor(name), "header": decl.header})
        search_source = "// Generated by dy_engine_docs/component/generate.py.\nwindow.RHI_SEARCH = " + json.dumps(search, ensure_ascii=False, separators=(",", ":")) + ";\n"
        self.search_version = hashlib.sha256(search_source.encode("utf-8")).hexdigest()[:12]
        self.index_pages()
        self.header_pages()
        self.authored_guides()
        for key, decl in self.api_pages.items():
            self.symbol_page(key, decl)
        self.pages["component/assets/search-index.js"] = search_source
        self.pages["component/manifest.json"] = json.dumps({
            "generator": "dy_engine_docs/component/generate.py", "source_root": self.source_label,
            "description_source": "header_comments_and_authored_guides" if self.editorial else "header_comments", "namespaces": self.namespaces,
            "authored_api_count": len(self.editorial), "authored_files": self.authored_hashes,
            "diagnostics": self.diagnostics,
            "headers": {name: hashlib.sha256(source.encode("utf-8")).hexdigest() for name, source in self.sources.items()},
            "symbols": len(self.symbols), "search_entries": len(search),
            "pages": sorted(name for name in self.pages if name.endswith(".html")),
        }, ensure_ascii=False, indent=2) + "\n"
        return self.pages


def stale_files(output, pages):
    """Only remove generated documents in this output tree; keep authored files."""
    output = Path(output).resolve()
    candidates = list(output.glob("*.html")) + list((output / "component").glob("*.html"))
    stale = []
    for path in candidates:
        # Resolve before deletion so a symlink cannot escape the document root.
        resolved = path.resolve()
        if not resolved.is_relative_to(output):
            raise ValueError(f"Generated page escapes output directory: {path}")
        if path.relative_to(output).as_posix() not in pages:
            content = path.read_text(encoding="utf-8")
            if any(marker in content for marker in (MARKER, LEGACY_MARKER, PREVIOUS_MARKER)):
                stale.append(path)
    for name in ("manifest.json", "assets/search-index.js"):
        path = output / name
        if path.is_file():
            if not path.resolve().is_relative_to(output):
                raise ValueError(f"Generated file escapes output directory: {path}")
            content = path.read_text(encoding="utf-8")
            if '"generator": "docs/rhi/generate.py"' in content or content.startswith("// Generated by docs/rhi/generate.py."):
                stale.append(path)
    return stale


def main(argv=None):
    global ROOT
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--project-root", type=Path, help="Engine repository (default: containing repository, then ../dy_engine next to the documentation folder)")
    parser.add_argument("--source-dir", type=Path, help="Header directory to scan recursively (default: src/Public; relative paths start at the engine repository)")
    parser.add_argument("--check", action="store_true", help="Fail if generated documents differ from current headers")
    args = parser.parse_args(argv)
    try:
        if args.project_root is not None:
            ROOT = args.project_root.resolve()
        source_dir = args.source_dir
        if source_dir is not None and not source_dir.is_absolute():
            source_dir = ROOT / source_dir
        reference = Reference(headers=source_dir) if source_dir is not None else Reference()
        pages = reference.build()
        stale = stale_files(OUTPUT, pages)
        changed = [name for name, content in pages.items() if not (OUTPUT / name).exists()
                   or (OUTPUT / name).read_text(encoding="utf-8") != content]
        missing_assets = [name for name in ("docs.css", "docs.js", "theme.js") if not (HERE / "assets" / name).is_file()]
        if missing_assets:
            raise ValueError(f"Missing component assets: {', '.join(missing_assets)}")
        if args.check:
            if stale or changed:
                print("API documentation is stale. Run the generator again with the same --source-dir.", file=sys.stderr)
                for name in changed + [path.relative_to(OUTPUT).as_posix() for path in stale]:
                    print(f"  {name}", file=sys.stderr)
                return 1
        else:
            for name in changed:
                path = OUTPUT / name
                if not path.resolve().is_relative_to(OUTPUT.resolve()):
                    raise ValueError(f"Generated file escapes output directory: {path}")
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_text(pages[name], encoding="utf-8", newline="\n")
            for path in stale:
                path.unlink()
        print(f"{'Verified' if args.check else 'Generated'} {len(reference.symbols)} API entries from {len(reference.sources)} headers; {sum(name.endswith('.html') for name in pages)} HTML pages.")
        if reference.diagnostics:
            print(f"{len(reference.diagnostics)} declarations require source review; see the affected header sections and component/manifest.json.", file=sys.stderr)
        return 0
    except (OSError, ValueError) as error:
        print(f"API documentation error: {error}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    sys.exit(main())
