file(GLOB directories RELATIVE "${CMAKE_CURRENT_SOURCE_DIR}" CONFIGURE_DEPENDS "[0-9][0-9]_*")
list(SORT directories)
set(advanced_targets)
foreach(directory IN LISTS directories)
    if(NOT IS_DIRECTORY "${CMAKE_CURRENT_SOURCE_DIR}/${directory}")
        continue()
    endif()
    add_subdirectory("${directory}")
    get_property(targets DIRECTORY "${CMAKE_CURRENT_SOURCE_DIR}/${directory}" PROPERTY BUILDSYSTEM_TARGETS)
    foreach(target IN LISTS targets)
        get_target_property(type "${target}" TYPE)
        if(NOT type STREQUAL "EXECUTABLE")
            continue()
        endif()
        set_property(TARGET ${target} PROPERTY FOLDER "Examples/advanced")
        list(APPEND advanced_targets "${target}")
    endforeach()
endforeach()
add_custom_target(AdvancedExamples DEPENDS ${advanced_targets})
