if(USE_D3D12)
	if(NOT WIN32)
		message(FATAL_ERROR "[${PROJECT_NAME}] D3D12 is only supported with Windows OS")
	endif()

	target_compile_definitions(Engine_Options PUBLIC ENABLE_D3D12)
	add_subdirectory(src/Backends/D3D12)
elseif(USE_METAL)
	if(NOT APPLE)
		message(FATAL_ERROR "[${PROJECT_NAME}] Metal is only supported with Mac OS")
	endif()

	target_compile_definitions(Engine_Options PUBLIC ENABLE_METAL)
	add_subdirectory(src/Backends/Metal)
elseif(USE_VULKAN)
	target_compile_definitions(Engine_Options PUBLIC ENABLE_VULKAN)
	add_subdirectory(src/Backends/)
else()
	add_subdirectory(src/Backends/Null)
endif()