# Apple and Linux use their platform backend; Windows selects one in the root CMakeLists.txt.
if(APPLE)
    message(STATUS "Apple: Metal")
    set(USE_METAL ON CACHE BOOL "Use the Metal backend." FORCE)
    set(USE_VULKAN OFF CACHE BOOL "Use the Vulkan backend." FORCE)
    set(USE_D3D12 OFF CACHE BOOL "Use the D3D12 backend." FORCE)
    enable_language(OBJCXX)
elseif(CMAKE_SYSTEM_NAME STREQUAL "Linux")
    message(STATUS "Linux: Vulkan")
    set(USE_VULKAN ON CACHE BOOL "Use the Vulkan backend." FORCE)
    set(USE_METAL OFF CACHE BOOL "Use the Metal backend." FORCE)
    set(USE_D3D12 OFF CACHE BOOL "Use the D3D12 backend." FORCE)
elseif(WIN32)
    message(STATUS "Windows")
else()
    message(FATAL_ERROR "Supported platforms are Windows, Apple and Linux.")
endif()

if(APPLE OR CMAKE_SYSTEM_NAME STREQUAL "Linux")
    # Keep inherited normal variables consistent with the platform cache values.
    foreach(backend IN ITEMS USE_D3D12 USE_METAL USE_VULKAN)
        set(${backend} "$CACHE{${backend}}")
    endforeach()
endif()

if(CMAKE_SYSTEM_NAME STREQUAL "Linux")
    set(DY_LINUX_WINDOW_SYSTEM "AUTO" CACHE STRING "Linux window system for GLFW: AUTO, X11, WAYLAND")
    set_property(CACHE DY_LINUX_WINDOW_SYSTEM PROPERTY STRINGS AUTO X11 WAYLAND)

    find_package(X11 QUIET)
    find_package(PkgConfig QUIET)

    set(DY_HAS_WAYLAND OFF)
    if(PkgConfig_FOUND)
        pkg_check_modules(WAYLAND_DEPS QUIET
            wayland-client
            wayland-cursor
            wayland-egl
            wayland-protocols
            xkbcommon
        )
        find_program(WAYLAND_SCANNER_EXECUTABLE wayland-scanner)
        if(WAYLAND_DEPS_FOUND AND WAYLAND_SCANNER_EXECUTABLE)
            set(DY_HAS_WAYLAND ON)
        endif()
    endif()

    if(DY_LINUX_WINDOW_SYSTEM STREQUAL "X11")
        if(NOT X11_FOUND)
            message(FATAL_ERROR "DY_LINUX_WINDOW_SYSTEM=X11 was requested, but X11 development packages were not found.")
        endif()
        message(STATUS "GLFW: using X11")
        set(GLFW_BUILD_X11 ON CACHE BOOL "" FORCE)
        set(GLFW_BUILD_WAYLAND OFF CACHE BOOL "" FORCE)
    elseif(DY_LINUX_WINDOW_SYSTEM STREQUAL "WAYLAND")
        if(NOT DY_HAS_WAYLAND)
            message(FATAL_ERROR "DY_LINUX_WINDOW_SYSTEM=WAYLAND was requested, but Wayland development packages were not found.")
        endif()
        message(STATUS "GLFW: using Wayland")
        set(GLFW_BUILD_X11 OFF CACHE BOOL "" FORCE)
        set(GLFW_BUILD_WAYLAND ON CACHE BOOL "" FORCE)
    elseif(DY_LINUX_WINDOW_SYSTEM STREQUAL "AUTO")
        if(X11_FOUND)
            message(STATUS "GLFW: using X11")
            set(GLFW_BUILD_X11 ON CACHE BOOL "" FORCE)
            set(GLFW_BUILD_WAYLAND OFF CACHE BOOL "" FORCE)
        elseif(DY_HAS_WAYLAND)
            message(STATUS "GLFW: using Wayland")
            set(GLFW_BUILD_X11 OFF CACHE BOOL "" FORCE)
            set(GLFW_BUILD_WAYLAND ON CACHE BOOL "" FORCE)
        else()
            message(FATAL_ERROR "Neither X11 nor Wayland development packages were found for GLFW.")
        endif()
    else()
        message(FATAL_ERROR "DY_LINUX_WINDOW_SYSTEM must be AUTO, X11, or WAYLAND.")
    endif()
endif()

# ===== ===== SIMD ===== =====
if(DY_ENABLE_SIMD)
	target_compile_definitions(Engine_Options INTERFACE DY_SIMD_ENABLED=1)

	if(CMAKE_SYSTEM_PROCESSOR MATCHES "^(x86|i[3-6]86)$")
		if(MSVC)
			target_compile_options(Engine_Options INTERFACE /arch:SSE2)
		elseif(CMAKE_CXX_COMPILER_ID MATCHES "GNU|Clang|AppleClang")
			target_compile_options(Engine_Options INTERFACE -msse2)
		endif()
	endif()
endif()
