# Support exceptions live beside each example; CMake generates the inventory.
include_guard(GLOBAL)
option(DY_CI "Build offline shaders and CI checks" OFF)
if(USE_D3D12)
    set(DY_SUPPORT_API d3d12)
elseif(USE_METAL)
    set(DY_SUPPORT_API metal)
elseif(USE_VULKAN)
    set(DY_SUPPORT_API vulkan)
else()
    set(DY_SUPPORT_API null)
endif()

# return() in this macro skips the caller's unsupported example before add_executable.
macro(dy_example_support)
    cmake_parse_arguments(DYES "" "KIND;REASON" "APIS;BUILD_ONLY" ${ARGN})
    if(DYES_UNPARSED_ARGUMENTS)
        message(FATAL_ERROR "Unknown support arguments: ${DYES_UNPARSED_ARGUMENTS}")
    endif()
    if(NOT DYES_KIND)
        set(DYES_KIND render)
    endif()
    if(NOT DYES_KIND MATCHES "^(render|window|cpu)$")
        message(FATAL_ERROR "Invalid example KIND: ${DYES_KIND}")
    endif()
    if(NOT DYES_APIS)
        set(DYES_APIS vulkan d3d12 metal)
    endif()
    foreach(api IN LISTS DYES_APIS DYES_BUILD_ONLY)
        if(NOT api MATCHES "^(vulkan|d3d12|metal)$")
            message(FATAL_ERROR "Invalid example API: ${api}")
        endif()
    endforeach()
    foreach(api IN LISTS DYES_BUILD_ONLY)
        if(NOT api IN_LIST DYES_APIS)
            message(FATAL_ERROR "BUILD_ONLY must also be in APIS: ${api}")
        endif()
    endforeach()
    set_property(DIRECTORY PROPERTY DY_EXAMPLE_KIND "${DYES_KIND}")
    set_property(DIRECTORY PROPERTY DY_EXAMPLE_APIS "${DYES_APIS}")
    set_property(DIRECTORY PROPERTY DY_EXAMPLE_BUILD_ONLY "${DYES_BUILD_ONLY}")
    set_property(DIRECTORY PROPERTY DY_EXAMPLE_REASON "${DYES_REASON}")
    if(DY_SUPPORT_API STREQUAL "null")
        if((DY_CI AND NOT DYES_KIND STREQUAL "cpu") OR
           NOT "vulkan" IN_LIST DYES_APIS OR NOT "d3d12" IN_LIST DYES_APIS OR NOT "metal" IN_LIST DYES_APIS)
            set_property(DIRECTORY PROPERTY DY_EXAMPLE_EXCLUDED TRUE)
            return()
        endif()
    elseif(NOT DY_SUPPORT_API IN_LIST DYES_APIS)
        set_property(DIRECTORY PROPERTY DY_EXAMPLE_EXCLUDED TRUE)
        return()
    endif()
endmacro()

function(dy_json_quote output value)
    string(REPLACE "\\" "\\\\" value "${value}")
    string(REPLACE "\"" "\\\"" value "${value}")
    string(REPLACE "\n" "\\n" value "${value}")
    string(REPLACE "\r" "\\r" value "${value}")
    string(REPLACE "\t" "\\t" value "${value}")
    string(REPLACE ";" "\\u003b" value "${value}")
    set(${output} "\"${value}\"" PARENT_SCOPE)
endfunction()

function(dy_example_shaders target)
    get_directory_property(kind DY_EXAMPLE_KIND)
    if(kind MATCHES "^(cpu|window)$" OR (DY_CI AND DY_SUPPORT_API STREQUAL "null"))
        return() # Null has no shader compiler or GPU execution requirement.
    endif()
    get_directory_property(build_only DY_EXAMPLE_BUILD_ONLY)
    if(DY_SUPPORT_API IN_LIST build_only)
        return()
    endif()
    if(DY_SUPPORT_API STREQUAL "d3d12")
        set(extension hlsl)
    elseif(DY_SUPPORT_API STREQUAL "metal")
        set(extension metal)
    else()
        set(extension glsl)
    endif()
    set(shader_directory "${CMAKE_CURRENT_SOURCE_DIR}/Shaders")
    if(ARGC GREATER 1)
        set(shader_directory "${ARGV1}")
    endif()
    set_property(TARGET "${target}" APPEND PROPERTY DY_CI_INPUTS "${shader_directory}")
    file(GLOB_RECURSE shaders CONFIGURE_DEPENDS "${shader_directory}/*.${extension}")
    if(NOT shaders)
        message(FATAL_ERROR "${target}/${DY_SUPPORT_API}: no ${extension} shaders; declare BUILD_ONLY for unimplemented APIs")
    endif()
    # Explicit config directory works with Ninja and multi-config generators alike.
    set(binary_dir "${CMAKE_CURRENT_BINARY_DIR}/$<CONFIG>")
    set_target_properties(${target} PROPERTIES RUNTIME_OUTPUT_DIRECTORY "${binary_dir}")
    file(GLOB_RECURSE includes CONFIGURE_DEPENDS "${CMAKE_SOURCE_DIR}/src/*.h"
        "${CMAKE_SOURCE_DIR}/src/*.inc" "${CMAKE_CURRENT_SOURCE_DIR}/Shaders/*.inc")
    set(outputs)
    foreach(input IN LISTS shaders)
        get_filename_component(stem "${input}" NAME_WE)
        if(stem MATCHES "_vs($|_)")
            set(stage vert)
            set(hlsl_stage vs_5_1)
        elseif(stem MATCHES "_hs($|_)")
            set(stage tesc)
            set(hlsl_stage hs_5_1)
        elseif(stem MATCHES "_ds($|_)")
            set(stage tese)
            set(hlsl_stage ds_5_1)
        elseif(stem MATCHES "_ps($|_)")
            set(stage frag)
            set(hlsl_stage ps_5_1)
        elseif(stem MATCHES "_cs($|_)")
            set(stage comp)
            set(hlsl_stage cs_5_1)
        else()
            message(FATAL_ERROR "${target}: unknown shader stage: ${input}; use _vs, _hs, _ds, _ps or _cs")
        endif()
        file(RELATIVE_PATH relative "${shader_directory}" "${input}")
        set(runtime "${binary_dir}/Shaders/${relative}")
        get_filename_component(runtime_dir "${runtime}" DIRECTORY)
        if(DY_SUPPORT_API STREQUAL "vulkan")
            find_program(DY_GLSLC NAMES glslc HINTS "$ENV{VULKAN_SDK}/Bin" "$ENV{VULKAN_SDK}/bin" REQUIRED)
            string(REGEX REPLACE "\\.glsl$" ".spv" runtime "${runtime}")
            add_custom_command(OUTPUT "${runtime}"
                COMMAND "${CMAKE_COMMAND}" -E make_directory "${runtime_dir}"
                COMMAND "${DY_GLSLC}" "-fshader-stage=${stage}" -I "${CMAKE_SOURCE_DIR}/src" "${input}" -o "${runtime}"
                DEPENDS "${input}" ${includes} VERBATIM)
            list(APPEND outputs "${runtime}")
        else()
            add_custom_command(OUTPUT "${runtime}"
                COMMAND "${CMAKE_COMMAND}" -E make_directory "${runtime_dir}"
                COMMAND "${CMAKE_COMMAND}" -E copy_if_different "${input}" "${runtime}"
                DEPENDS "${input}" ${includes} VERBATIM)
            list(APPEND outputs "${runtime}")
            if(DY_CI AND NOT DY_SUPPORT_API STREQUAL "null")
                set(offline "${CMAKE_BINARY_DIR}/ci-shaders/$<CONFIG>/${target}/${relative}.bin")
                get_filename_component(offline_dir "${offline}" DIRECTORY)
                if(DY_SUPPORT_API STREQUAL "d3d12")
                    find_program(DY_FXC NAMES fxc REQUIRED)
                    set(command "${DY_FXC}" /nologo /enable_unbounded_descriptor_tables /E main /T "${hlsl_stage}"
                        /I "${CMAKE_SOURCE_DIR}/src" "${input}" /Fo "${offline}")
                else()
                    include(MetalToolchain)
                    set(command "${DY_XCRUN}" ${DY_METAL_XCRUN_ARGS} metal -c "${input}" -I "${CMAKE_SOURCE_DIR}/src" -o "${offline}")
                endif()
                add_custom_command(OUTPUT "${offline}"
                    COMMAND "${CMAKE_COMMAND}" -E make_directory "${offline_dir}"
                    COMMAND ${command} DEPENDS "${input}" ${includes} VERBATIM)
                list(APPEND outputs "${offline}")
            endif()
        endif()
    endforeach()
    add_custom_target("ci_shaders_${target}" ALL DEPENDS ${outputs})
    add_dependencies(${target} "ci_shaders_${target}")
    set_property(TARGET "${target}" PROPERTY DY_CI_SHADER_OUTPUTS "${outputs}")
endfunction()

function(dy_collect_example_targets directory output)
    get_property(targets DIRECTORY "${directory}" PROPERTY BUILDSYSTEM_TARGETS)
    set(result)
    foreach(target IN LISTS targets)
        get_target_property(type "${target}" TYPE)
        if(type STREQUAL "EXECUTABLE")
            list(APPEND result "${target}")
        endif()
    endforeach()
    get_property(children DIRECTORY "${directory}" PROPERTY SUBDIRECTORIES)
    foreach(child IN LISTS children)
        dy_collect_example_targets("${child}" nested)
        list(APPEND result ${nested})
    endforeach()
    set(${output} "${result}" PARENT_SCOPE)
endfunction()

function(dy_example_assets target source destination)
    if(NOT destination MATCHES "^[A-Za-z0-9_-]+$")
        message(FATAL_ERROR "Asset destination must be a simple directory name")
    endif()
    get_filename_component(input_directory "${source}" ABSOLUTE)
    set_property(TARGET "${target}" APPEND PROPERTY DY_CI_INPUTS "${input_directory}")
    add_custom_target("ci_assets_${target}_${destination}" ALL
        COMMAND "${CMAKE_COMMAND}" "-DSOURCE=${source}"
            "-DDESTINATION=$<TARGET_FILE_DIR:${target}>/${destination}"
            "-DBUILD_ROOT=${CMAKE_BINARY_DIR}" -P "${CMAKE_SOURCE_DIR}/cmake/SyncAssets.cmake"
        VERBATIM)
    add_dependencies(${target} "ci_assets_${target}_${destination}")
endfunction()

function(dy_target_inputs target output complete visited)
    if(target IN_LIST visited)
        set(${output} "" PARENT_SCOPE)
        set(${complete} true PARENT_SCOPE)
        return()
    endif()
    list(APPEND visited "${target}")
    set(inputs)
    set(known true)
    get_target_property(directory "${target}" SOURCE_DIR)
    foreach(property SOURCES DY_CI_INPUTS)
        get_target_property(values "${target}" "${property}")
        if(values)
            foreach(value IN LISTS values)
                if(value MATCHES "^\\$<TARGET_OBJECTS:([^>]+)>$")
                    dy_target_inputs("${CMAKE_MATCH_1}" nested nested_known "${visited}")
                    list(APPEND inputs ${nested})
                    if(NOT nested_known)
                        set(known false)
                    endif()
                elseif(value MATCHES "\\$<")
                    set(known false)
                else()
                    get_filename_component(input "${value}" ABSOLUTE BASE_DIR "${directory}")
                    list(APPEND inputs "${input}")
                endif()
            endforeach()
        endif()
    endforeach()
    foreach(property LINK_LIBRARIES INTERFACE_LINK_LIBRARIES)
        get_target_property(links "${target}" "${property}")
        if(links)
            foreach(link IN LISTS links)
                if(link MATCHES "^\\$<LINK_ONLY:([^>]+)>$")
                    set(link "${CMAKE_MATCH_1}")
                endif()
                if(TARGET "${link}")
                    dy_target_inputs("${link}" nested nested_known "${visited}")
                    list(APPEND inputs ${nested})
                    if(NOT nested_known)
                        set(known false)
                    endif()
                elseif(link MATCHES "\\$<")
                    set(known false)
                elseif(IS_ABSOLUTE "${link}")
                    list(APPEND inputs "${link}")
                endif()
            endforeach()
        endif()
    endforeach()
    list(REMOVE_DUPLICATES inputs)
    set(${output} "${inputs}" PARENT_SCOPE)
    set(${complete} "${known}" PARENT_SCOPE)
endfunction()

function(dy_target_input_json target output)
    dy_target_inputs("${target}" inputs complete "")
    set(values)
    foreach(input IN LISTS inputs)
        dy_json_quote(quoted "${input}")
        list(APPEND values "${quoted}")
    endforeach()
    list(JOIN values "," values)
    set(${output} "\"inputs\":[${values}],\"inputs_complete\":${complete}" PARENT_SCOPE)
endfunction()

function(dy_discover_examples)
    file(GLOB declarations CONFIGURE_DEPENDS "${CMAKE_CURRENT_SOURCE_DIR}/*/CMakeLists.txt")
    foreach(declaration IN LISTS declarations)
        get_filename_component(directory "${declaration}" DIRECTORY)
        file(RELATIVE_PATH relative "${CMAKE_SOURCE_DIR}" "${directory}")
        add_subdirectory("${directory}" "${CMAKE_BINARY_DIR}/${relative}")
    endforeach()
    dy_write_example_manifest()
endfunction()

# Read the configured CMake tree: containers and nested examples need no flat naming convention.
function(dy_write_example_manifest)
    set(entries)
    set(paths)
    set(unsupported)
    set(directories "${CMAKE_CURRENT_SOURCE_DIR}")
    while(directories)
        list(POP_FRONT directories directory)
        get_property(children DIRECTORY "${directory}" PROPERTY SUBDIRECTORIES)
        list(APPEND directories ${children})
        file(RELATIVE_PATH relative "${CMAKE_SOURCE_DIR}" "${directory}")
        get_property(excluded DIRECTORY "${directory}" PROPERTY DY_EXAMPLE_EXCLUDED)
        get_property(kind DIRECTORY "${directory}" PROPERTY DY_EXAMPLE_KIND)
        get_property(build_only DIRECTORY "${directory}" PROPERTY DY_EXAMPLE_BUILD_ONLY)
        get_property(reason DIRECTORY "${directory}" PROPERTY DY_EXAMPLE_REASON)
        if(NOT kind)
            set(kind render)
        endif()
        dy_json_quote(dir_json "${relative}")
        if(excluded)
            if(NOT reason)
                set(reason "API excluded by example support declaration")
            endif()
            dy_json_quote(reason_json "${reason}")
            list(APPEND unsupported "{\"directory\":${dir_json},\"reason\":${reason_json}}")
            continue()
        endif()
        get_property(targets DIRECTORY "${directory}" PROPERTY BUILDSYSTEM_TARGETS)
        foreach(target IN LISTS targets)
            get_target_property(type "${target}" TYPE)
            if(NOT type STREQUAL "EXECUTABLE")
                continue()
            endif()
            get_target_property(source_directory "${target}" SOURCE_DIR)
            set_property(TARGET "${target}" APPEND PROPERTY DY_CI_INPUTS "${source_directory}")
            foreach(assets Assets Models Textures)
                if(IS_DIRECTORY "${source_directory}/${assets}" AND NOT TARGET "ci_assets_${target}_${assets}")
                    dy_example_assets("${target}" "${source_directory}/${assets}" "${assets}")
                endif()
            endforeach()
            get_target_property(sources "${target}" SOURCES)
            set(source_json)
            foreach(source IN LISTS sources)
                get_filename_component(source "${source}" ABSOLUTE BASE_DIR "${source_directory}")
                dy_json_quote(quoted "${source}")
                list(APPEND source_json "${quoted}")
            endforeach()
            list(JOIN source_json "," source_json)
            set(runtime true)
            if(DY_SUPPORT_API IN_LIST build_only OR (DY_SUPPORT_API STREQUAL "null" AND NOT kind STREQUAL "cpu"))
                set(runtime false)
                if(NOT reason)
                    set(reason "Build only; runtime support is not implemented")
                endif()
            endif()
            get_target_property(shader_outputs "${target}" DY_CI_SHADER_OUTPUTS)
            set(shader_json)
            if(shader_outputs)
                foreach(shader IN LISTS shader_outputs)
                    dy_json_quote(quoted "${shader}")
                    list(APPEND shader_json "${quoted}")
                endforeach()
            endif()
            list(JOIN shader_json "," shader_json)
            dy_target_input_json("${target}" input_json)
            dy_json_quote(reason_json "${reason}")
            list(APPEND paths "\"${target}\":\"$<TARGET_FILE:${target}>\"")
            list(APPEND entries "{\"name\":\"${target}\",\"binary\":\"$<TARGET_FILE:${target}>\",\"directory\":${dir_json},\"kind\":\"${kind}\",\"runtime\":${runtime},\"reason\":${reason_json},\"sources\":[${source_json}],\"shaders\":[${shader_json}],${input_json}}")
        endforeach()
    endwhile()
    list(JOIN entries ",\n" entries)
    list(JOIN unsupported ",\n" unsupported)
    list(JOIN paths ",\n" paths)
    dy_json_quote(compiler "${CMAKE_CXX_COMPILER_ID} ${CMAKE_CXX_COMPILER_VERSION} (${CMAKE_CXX_COMPILER})")
    file(GENERATE OUTPUT "${CMAKE_BINARY_DIR}/ci-manifest-$<CONFIG>.json"
        CONTENT "{\"version\":1,\"api\":\"${DY_SUPPORT_API}\",\"config\":\"$<CONFIG>\",\"compiler\":${compiler},\"targets\":[${entries}],\"unsupported\":[${unsupported}]}\n")
    file(GENERATE OUTPUT "${CMAKE_BINARY_DIR}/ci-targets-$<CONFIG>.json" CONTENT "{${paths}}\n")
endfunction()
