# Build and deploy the optional native observer; file logging remains platform-independent.
set(dy_log_monitor_supported OFF)
if(WIN32 AND MSVC AND CMAKE_SIZEOF_VOID_P EQUAL 8
   AND NOT CMAKE_GENERATOR_PLATFORM MATCHES "[Aa][Rr][Mm]64"
   AND NOT CMAKE_SYSTEM_PROCESSOR MATCHES "^(ARM64|arm64|aarch64)$")
    set(dy_log_monitor_supported ON)
endif()
option(DY_LOG_CRASH_MONITOR "Build and deploy the Windows x64 crash monitor." ${dy_log_monitor_supported})
if(DY_LOG_CRASH_MONITOR)
    if(NOT dy_log_monitor_supported)
        message(FATAL_ERROR "DY_LOG_CRASH_MONITOR requires Windows x64 and MSVC.")
    endif()
    add_executable(dy_log_monitor "${CMAKE_CURRENT_LIST_DIR}/../src/Platform/WindowsLogMonitor.cpp")
    set_target_properties(dy_log_monitor PROPERTIES OUTPUT_NAME windows_monitor)
    target_compile_features(dy_log_monitor PRIVATE cxx_std_17)
    target_compile_definitions(dy_log_monitor PRIVATE UNICODE _UNICODE WIN32_LEAN_AND_MEAN NOMINMAX)
    target_compile_options(dy_log_monitor PRIVATE /W4 /utf-8)
    target_link_libraries(dy_log_monitor PRIVATE dbghelp)
endif()

# Defer until applications declared after add_subdirectory(dy_engine) exist.
function(dy_deploy_runtime)
    set(runtime_files)
    foreach(runtime IN ITEMS dy_log_monitor WinPixEventRuntime)
        if(TARGET ${runtime})
            list(APPEND runtime_files "$<TARGET_FILE:${runtime}>")
        endif()
    endforeach()
    if(NOT runtime_files)
        return()
    endif()

    set(copy_script "${CMAKE_CURRENT_BINARY_DIR}/CMakeFiles/dy_runtime-$<CONFIG>.cmake")
    add_custom_target(dy_runtime COMMAND "${CMAKE_COMMAND}" -P "${copy_script}" VERBATIM)
    if(TARGET dy_log_monitor)
        add_dependencies(dy_runtime dy_log_monitor)
    endif()
    set(directories "${CMAKE_SOURCE_DIR}")
    set(destinations)
    while(directories)
        list(POP_FRONT directories directory)
        get_property(targets DIRECTORY "${directory}" PROPERTY BUILDSYSTEM_TARGETS)
        foreach(target IN LISTS targets)
            get_target_property(kind "${target}" TYPE)
            if(kind STREQUAL "EXECUTABLE" AND NOT target STREQUAL "dy_log_monitor")
                add_dependencies(${target} dy_runtime)
                list(APPEND destinations "$<TARGET_FILE_DIR:${target}>")
            endif()
        endforeach()
        get_property(children DIRECTORY "${directory}" PROPERTY SUBDIRECTORIES)
        list(APPEND directories ${children})
    endwhile()
    # Resolve paths here so CMP0112 OLD cannot add consumer dependencies.
    # The shared target refreshes runtime changes without relinking consumers.
    file(GENERATE OUTPUT "${copy_script}" CONTENT
"set(files [==[${runtime_files}]==])
set(directories [==[${destinations}]==])
list(REMOVE_DUPLICATES directories)
foreach(directory IN LISTS directories)
    file(MAKE_DIRECTORY \"\${directory}\")
    execute_process(COMMAND [==[${CMAKE_COMMAND}]==] -E copy_if_different
        \${files} \"\${directory}\" COMMAND_ERROR_IS_FATAL ANY)
endforeach()
")
endfunction()
cmake_language(DEFER DIRECTORY "${CMAKE_SOURCE_DIR}" CALL dy_deploy_runtime)
