#!/usr/bin/env python3
"""Build the offline RHI reference from src/Public/RHI (Python standard library only).

This intentionally supports the declaration style of this project's public headers,
not arbitrary C++. Unknown declarations or undocumented symbols fail the build.
"""

from __future__ import annotations

import argparse
from collections import Counter
from dataclasses import dataclass, field
import hashlib
import html
import json
from pathlib import Path
import re
import sys
import textwrap

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent.parent
HEADERS = ROOT / "src/Public/RHI"
MARKER = "<!-- Generated by docs/rhi/generate.py. -->"
KINDS = {"class": "클래스", "struct": "구조체", "enum": "열거형", "alias": "형식 별칭", "function": "함수"}
GROUPS = [
    ("device", "디바이스와 명령", ["IDevice.h", "ICommandList.h", "Swapchain.h"]),
    ("resources", "리소스와 수명", ["Buffer.h", "Texture.h", "ResourceHandles.h", "ResourceScope.h"]),
    ("pipeline", "셰이더와 파이프라인", ["Shader.h", "Pipeline.h"]),
    ("binding", "리소스 바인딩", ["Binding.h", "ResourceSet.h"]),
    ("rendering", "렌더링과 동기화", ["Rendering.h", "Barrier.h", "ResourceState.h", "Format.h", "Readback.h"]),
    ("graph", "렌더 그래프", ["RenderGraph.h"]),
]


@dataclass
class Decl:
    name: str
    kind: str
    header: str
    line: int
    syntax: str
    members: list[Decl] = field(default_factory=list)
    value: str = ""

    @property
    def page(self):
        return "api-" + slug(self.name) + ".html"


def slug(value):
    value = value.replace("operator", "operator-")
    for token, word in [("|", "or"), ("&", "and"), ("=", "equal"), ("!", "not"), ("~", "destructor-")]:
        value = value.replace(token, word)
    return re.sub(r"[^a-z0-9-]+", "-", value.lower()).strip("-")


def masked(source):
    # Preserve offsets and newlines while ignoring comments and quoted braces.
    return re.sub(r'//[^\n]*|/\*[\s\S]*?\*/|"(?:\\.|[^"\\])*"|\'(?:\\.|[^\'\\])*\'',
                  lambda m: re.sub(r"[^\n]", " ", m.group()), source)


def closing(code, start, left="{", right="}"):
    depth = 0
    for pos in range(start, len(code)):
        if code[pos] == left:
            depth += 1
        elif code[pos] == right:
            depth -= 1
            if not depth:
                return pos
    raise ValueError(f"Unclosed {left} at {start}")


def clean(text):
    text = re.sub(r"//[^\n]*|/\*[\s\S]*?\*/", "", text)
    return textwrap.dedent(text.expandtabs(4)).strip()


def compact(text):
    return re.sub(r"\s+", " ", clean(text)).strip()


def statements(source, offset=0):
    """Yield declarations and access labels, skipping inline function bodies."""
    code = masked(source)
    pos = 0
    while pos < len(code):
        if code[pos].isspace() or code[pos] == ";":
            pos += 1
            continue
        access = re.match(r"(public|protected|private)\s*:", code[pos:])
        if access:
            yield access.group(1), "access", offset + pos, ""
            pos += access.end()
            continue
        start = pos
        parens = brackets = 0
        while pos < len(code):
            ch = code[pos]
            if ch == "(":
                parens += 1
            elif ch == ")":
                parens -= 1
            elif ch == "[":
                brackets += 1
            elif ch == "]":
                brackets -= 1
            elif ch == "{" and parens == 0 and brackets == 0:
                end = closing(code, pos)
                prefix = compact(source[start:pos])
                if re.match(r"(?:enum\s+class|class|struct|namespace)\b", prefix):
                    yield source[start:end + 1], "block", offset + start, source[pos + 1:end]
                    pos = end + 1
                    break
                if "(" in prefix and not re.search(r"\s=\s", prefix):
                    # Constructor member initializers are not part of the signature.
                    prefix = re.split(r"\)\s*:(?!:)", prefix, maxsplit=1)[0]
                    if not prefix.endswith(")") and re.search(r"\)\s*:(?!:)", compact(source[start:pos])):
                        prefix += ")"
                    yield prefix.rstrip(";") + ";", "method", offset + start, ""
                    pos = end + 1
                    break
                pos = end
            elif ch == ";" and parens == 0 and brackets == 0:
                yield source[start:pos + 1], "statement", offset + start, ""
                pos += 1
                break
            pos += 1
        else:
            if code[start:].strip():
                raise ValueError(f"Unparsed declaration: {source[start:start + 100]}")


def function_name(syntax):
    match = re.search(r"(operator\s*(?:\|=|&=|==|!=|=|\||&)|~?\w+)\s*\(", syntax)
    if not match:
        raise ValueError(f"Unknown function: {syntax}")
    return match.group(1).replace(" ", "")


def parse_header(path, source=None):
    if source is None:
        source = path.read_text(encoding="utf-8")
    code = masked(source)
    declarations = []
    for namespace in re.finditer(r"namespace\s+dy::RHI\s*\{", code):
        begin = namespace.end()
        end = closing(code, begin - 1)
        for raw, mode, pos, body in statements(source[begin:end], begin):
            syntax = compact(raw)
            line = source.count("\n", 0, pos) + 1
            match = re.match(r"(enum\s+class|class|struct)\s+(\w+)", syntax)
            if match:
                if mode != "block":  # Forward declarations have their own definition elsewhere.
                    continue
                kind, name = match.groups()
                kind = "enum" if kind.startswith("enum") else kind
                declaration = Decl(name, kind, path.name, line, clean(raw) + ";")
                body_pos = pos + raw.index("{") + 1
                if kind == "enum":
                    body_code = re.sub(r"//[^\n]*|/\*[\s\S]*?\*/", "", body)
                    next_value = 0
                    for value in body_code.split(","):
                        value = compact(value)
                        if not value:
                            continue
                        parts = value.split("=", 1)
                        enum_value = parts[1].strip() if len(parts) == 2 else f"{next_value} (암시적)"
                        if len(parts) == 2:
                            literal = re.fullmatch(r"(0x[\da-fA-F]+|\d+)[uUlL]*", parts[1].strip())
                            next_value = int(literal.group(1), 0) if literal else None
                        elif next_value is None:
                            raise ValueError(f"Cannot resolve implicit enum value: {name}::{parts[0]}")
                        declaration.members.append(Decl(parts[0].strip(), "value", path.name, line, value,
                                                        value=enum_value))
                        if next_value is not None:
                            next_value += 1
                else:
                    access = "public" if kind == "struct" else "private"
                    for member, member_mode, member_pos, _ in statements(body, body_pos):
                        if member_mode == "access":
                            access = member
                            continue
                        if access != "public":
                            continue
                        member = compact(member)
                        is_method = bool(re.search(r"(?:operator\s*[^\s(]+|~?\w+)\s*\(", member.split(" = ")[0]))
                        member_name = function_name(member) if is_method else re.search(r"(\w+)(?:\[[^]]*\])?\s*(?:=|;)", member).group(1)
                        declaration.members.append(Decl(member_name, "method" if is_method else "field", path.name,
                                                        source.count("\n", 0, member_pos) + 1, member))
                    lines = [m.syntax for m in declaration.members]
                    # Only public API in the synopsis; full source is on the header page.
                    declaration.syntax = f"{kind} {name}\n{{\n" + ("public:\n" if kind == "class" else "") + "\n".join("    " + s for s in lines) + "\n};"
                declarations.append(declaration)
            elif syntax.startswith("using "):
                declarations.append(Decl(re.match(r"using\s+(\w+)", syntax).group(1), "alias", path.name, line, syntax))
            elif "(" in syntax:
                declarations.append(Decl(function_name(syntax), "function", path.name, line, syntax))
            else:
                raise ValueError(f"Unknown declaration in {path.name}: {syntax}")
    return declarations


def escape(value):
    return html.escape(str(value), quote=True)


class Reference:
    def __init__(self):
        self.sources = {path.name: path.read_text(encoding="utf-8") for path in sorted(HEADERS.glob("*.h"))}
        parsed = [decl for name, source in self.sources.items() for decl in parse_header(HEADERS / name, source)]
        self.symbols = {}
        for decl in parsed:
            key = decl.name if decl.kind != "function" or not decl.name.startswith("operator") else f"{Path(decl.header).stem}-{decl.name}"
            if key in self.symbols:
                raise ValueError(f"Duplicate symbol: {key}")
            self.symbols[key] = decl
        self.docs = json.loads((HERE / "reference.json").read_text(encoding="utf-8"))
        self.pages = {}
        self.current = ""
        self.validate_docs()

    def doc(self, name):
        return self.docs["symbols"].get(name, {})

    def summary(self, decl):
        if decl.name.startswith("operator") and decl.kind == "function":
            flag = re.search(r"\(\s*(\w+)", decl.syntax).group(1)
            return f"{flag} 비트 플래그에 {decl.name[8:]} 연산을 적용합니다."
        return self.doc(decl.name)["summary"]

    def member_doc(self, decl, member):
        entry = self.doc(decl.name).get("members", {}).get(member.name)
        if entry is None:
            entry = self.docs["common_members"].get(member.name)
        if entry is None and member.name == decl.name:
            entry = f"{decl.name} 객체를 생성합니다. 복사·이동 가능 여부는 각 선언의 default / delete를 확인하세요."
        if entry is None and member.name == "~" + decl.name:
            entry = f"{decl.name} 객체를 소멸합니다. 리소스 해제 규칙은 설명을 참고하세요."
        if entry is None:
            raise ValueError(f"Missing documentation: {decl.name}::{member.name}")
        return {"summary": entry} if isinstance(entry, str) else entry

    def validate_docs(self):
        missing = [d.name for d in self.symbols.values() if not d.name.startswith("operator") and d.name not in self.docs["symbols"]]
        if missing:
            raise ValueError(f"Undocumented symbols: {', '.join(missing)}")
        for decl in self.symbols.values():
            for member in decl.members:
                self.member_doc(decl, member)

    def url(self, key):
        decl = self.symbols[key]
        return ("api-" + slug(key) + ".html") if key != decl.name else decl.page

    def rich(self, value):
        def inline(match):
            name = match.group(1)
            key, _, member = name.partition("::")
            label = f"<code>{escape(name)}</code>"
            if key in self.symbols:
                url = self.url(key) + ("#" + slug(member) if member else "")
                return f'<a href="{url}">{label}</a>'
            return label
        parts = re.split(r"(`[^`]+`)", value)
        return "".join(inline(re.fullmatch(r"`([^`]+)`", part)) if part.startswith("`") and part.endswith("`") else escape(part) for part in parts)

    def paragraphs(self, values):
        return "".join(f"<p>{self.rich(value)}</p>" for value in values)

    def link(self, key, label=None):
        return f'<a href="{self.url(key)}"><code>{escape(label or self.symbols[key].name)}</code></a>'

    def code(self, source):
        return '<div class="code-block"><div class="code-bar"><span>C++</span><button class="copy-button" type="button">복사</button></div><pre><code class="language-cpp">' + escape(source) + '</code></pre></div>'

    def table(self, headings, rows):
        return '<div class="table-scroll"><table><thead><tr>' + "".join(f"<th scope=\"col\">{escape(h)}</th>" for h in headings) + '</tr></thead><tbody>' + "".join('<tr>' + "".join(f"<td>{c}</td>" for c in row) + '</tr>' for row in rows) + '</tbody></table></div>'

    def sidebar(self):
        result = '<p class="nav-heading">RHI 문서</p>'
        for url, title in [("index.html", "개요"), ("getting-started.html", "시작하기"), ("api-index.html", "API 찾아보기"), ("headers.html", "헤더 파일")]:
            result += f'<a class="nav-link{" current" if self.current == url else ""}" href="{url}"' + (' aria-current="page"' if self.current == url else '') + f'>{title}</a>'
        result += '<div class="nav-divider"></div><p class="nav-heading">API 참조</p>'
        for group, title, headers in GROUPS:
            values = [(key, d) for key, d in self.symbols.items() if d.header in headers and d.kind != "function"]
            is_current = any(self.url(key) == self.current for key, _ in values)
            result += f'<details class="nav-group" data-group="{group}"' + (' open' if is_current or self.current == "index.html" and group == "device" else '') + f'><summary>{title}<span>{len(values)}</span></summary>'
            for key, decl in sorted(values, key=lambda pair: ({"class": 0, "struct": 1, "enum": 2, "alias": 3}[pair[1].kind], pair[0])):
                current = self.current == self.url(key)
                result += f'<a class="nav-symbol{" current" if current else ""}" href="{self.url(key)}"' + (' aria-current="page"' if current else '') + f'><span class="type-icon {decl.kind}" aria-label="{KINDS[decl.kind]}">{ {"class": "C", "struct": "S", "enum": "E", "alias": "T"}[decl.kind]}</span>{escape(decl.name)}</a>'
            result += '</details>'
        result += '<a class="nav-link" href="api-index.html#functions">함수와 연산자</a>'
        return result

    def page(self, filename, title, description, content, toc, category="문서", meta="C++17 · dy::RHI"):
        self.current = filename
        toc_html = "".join(f'<a href="#{anchor}">{escape(label)}</a>' for anchor, label in toc)
        crumb = f'<a href="index.html">문서</a><span>/</span><a href="api-index.html">RHI</a><span>/</span><span>{escape(category)}</span>'
        self.pages[filename] = f'''<!doctype html>
{MARKER}
<html lang="ko">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="description" content="{escape(description)}">
<meta name="color-scheme" content="light dark">
<title>{escape(title)} | dy_engine RHI 문서</title>
<script src="assets/theme.js"></script>
<link rel="stylesheet" href="assets/docs.css">
<script src="assets/search-index.js" defer></script>
<script src="assets/docs.js" defer></script>
</head>
<body>
<a class="skip-link" href="#main">본문으로 건너뛰기</a>
<header class="site-header">
  <a class="brand" href="index.html" aria-label="dy_engine 문서 홈"><span class="brand-mark" aria-hidden="true">dy</span><span>dy_engine</span></a>
  <span class="brand-divider"></span><a class="docs-brand" href="index.html">Docs</a>
  <nav class="top-nav" aria-label="주 메뉴"><a class="active" href="index.html">RHI</a><a href="getting-started.html">시작하기</a><a href="api-index.html">API 참조</a></nav>
  <div class="header-actions"><button class="search-trigger" type="button" aria-haspopup="dialog"><svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="10.5" cy="10.5" r="6.5"/><path d="m16 16 5 5"/></svg><span>문서 검색</span><kbd>/</kbd></button><button class="theme-toggle icon-button" type="button" aria-label="어두운 테마로 전환" title="테마 전환"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M20.8 14.2A9 9 0 0 1 9.8 3.2 9 9 0 1 0 20.8 14.2Z"/></svg></button></div>
</header>
<div class="product-bar"><div><button class="menu-toggle" type="button" aria-controls="sidebar" aria-expanded="false">☰ <span>목차</span></button><a href="index.html">Render Hardware Interface</a><span class="product-tag">C++ API</span><span class="product-version">공개 헤더 기준</span></div></div>
<div class="doc-layout">
<aside class="sidebar" id="sidebar" aria-label="문서 탐색"><div class="sidebar-inner"><button class="sidebar-search search-trigger" type="button" aria-haspopup="dialog"><span>API 이름으로 검색</span><kbd>/</kbd></button><nav aria-label="API 목차">{self.sidebar()}</nav><div class="sidebar-footer"><span class="status-dot"></span>로컬에서 읽는 API 레퍼런스</div></div></aside>
<button class="nav-backdrop" type="button" aria-label="목차 닫기" hidden></button>
<main id="main" tabindex="-1"><div class="breadcrumbs" aria-label="현재 위치">{crumb}</div><div class="article-topline"><span class="eyebrow">RHI REFERENCE</span><button class="print-button" type="button">인쇄</button></div><h1>{escape(title)}</h1><div class="article-meta">{meta}</div><p class="lead">{self.rich(description)}</p><nav class="mobile-toc" aria-label="이 문서의 내용"><details><summary>이 문서의 내용</summary>{toc_html}</details></nav>{content}<footer class="article-footer"><p>dy_engine · RHI API 참조</p><span>소스: src/Public/RHI · 한국어</span><a href="#main">맨 위로 ↑</a></footer></main>
<aside class="page-toc" aria-label="이 문서의 내용"><div><h2>이 문서의 내용</h2><nav>{toc_html}</nav><div class="toc-note"><span>C++</span><p>명시적인 리소스 관리.<br>백엔드 독립적인 API.</p></div></div></aside>
</div>
<dialog id="search-dialog" aria-labelledby="search-title"><div class="search-heading"><h2 id="search-title">RHI 문서 검색</h2><button type="button" class="close-search" aria-label="검색 닫기">닫기 <kbd>Esc</kbd></button></div><label class="search-field"><svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="10.5" cy="10.5" r="6.5"/><path d="m16 16 5 5"/></svg><input id="search-input" type="search" placeholder="API, 멤버 또는 설명 검색…" autocomplete="off" spellcheck="false" aria-label="검색어" aria-controls="search-results"></label><p id="search-status" role="status" aria-live="polite"></p><div id="search-results"></div><div class="search-footer"><span>↑ ↓ 결과 이동 · Enter 열기</span><span>전체 공개 API에서 검색</span></div></dialog>
<div class="toast" role="status" aria-live="polite"></div>
<noscript><div class="noscript-note">검색과 테마 전환에는 JavaScript가 필요합니다. 문서와 모든 API 링크는 그대로 이용할 수 있습니다.</div></noscript>
</body></html>
'''

    def source_link(self, header, line=1):
        return f'header-{Path(header).stem.lower()}.html#L{line}'

    def symbol_page(self, key, decl):
        doc = self.doc(decl.name)
        toc = [("syntax", "구문")]
        content = f'<section id="syntax"><h2>구문</h2>{self.code(decl.syntax)}</section>'
        fields = [m for m in decl.members if m.kind in ("field", "value")]
        methods = [m for m in decl.members if m.kind == "method"]
        if fields:
            label = "상수" if decl.kind == "enum" else "멤버 변수"
            field_anchor = "fields" if methods else "members"
            toc.append((field_anchor, label))
            rows = []
            for member in fields:
                detail = self.member_doc(decl, member)
                value = member.value if member.kind == "value" else member.syntax
                rows.append([f'<code id="{slug(member.name)}">{escape(member.name)}</code>', f'<code>{escape(value)}</code>', self.rich(detail["summary"])])
            content += f'<section id="{field_anchor}"><h2>{label}</h2>{self.table(["이름", "값" if decl.kind == "enum" else "선언과 기본값", "설명"], rows)}</section>'
        if methods:
            toc.append(("members", "멤버 함수"))
            unique = list(dict.fromkeys(m.name for m in methods))
            content += '<section id="members"><h2>멤버 함수</h2>' + self.table(["이름", "설명"], [[f'<a href="#{slug(name)}"><code>{escape(name)}</code></a>', self.rich(self.member_doc(decl, next(m for m in methods if m.name == name))["summary"])] for name in unique]) + '</section>'
        params = doc.get("params", {})
        returns = doc.get("returns")
        if decl.name.startswith("operator") and decl.kind == "function":
            params = {"left": "왼쪽 비트 플래그 값입니다. 대입 연산에서는 이 값을 갱신합니다.", "right": "오른쪽 비트 플래그 값입니다."}
            returns = "연산 결과인 플래그 값입니다. |=, &= 연산은 갱신한 left의 참조를 반환합니다."
        if params:
            toc.append(("parameters", "매개변수"))
            content += '<section id="parameters"><h2>매개변수</h2><dl class="parameters">' + "".join(f'<dt><code>{escape(p)}</code></dt><dd>{self.rich(desc)}</dd>' for p, desc in params.items()) + '</dl></section>'
        if returns:
            toc.append(("return-value", "반환 값"))
            content += '<section id="return-value"><h2>반환 값</h2><p>' + self.rich(returns) + '</p></section>'
        if doc.get("remarks"):
            toc.append(("remarks", "설명"))
            content += '<section id="remarks"><h2>설명</h2>' + self.paragraphs(doc["remarks"]) + '</section>'
        example = (HERE / "examples" / doc["example_file"]).read_text(encoding="utf-8") if doc.get("example_file") else doc.get("example")
        if example:
            toc.append(("example", "예제"))
            content += '<section id="example"><h2>예제</h2>' + self.code(example) + '</section>'
        toc.append(("requirements", "요구 사항"))
        content += '<section id="requirements"><h2>요구 사항</h2>' + self.table(["항목", "내용"], [
            ["헤더", f'<a href="{self.source_link(decl.header, decl.line)}"><code>&lt;RHI/{escape(decl.header)}&gt;</code></a>'],
            ["네임스페이스", "<code>dy::RHI</code>"], ["언어 표준", "C++17 이상"],
            ["Include 경로", "<code>src/Public</code>"],
        ]) + '</section>'
        for name in dict.fromkeys(m.name for m in methods):
            overloads = [m for m in methods if m.name == name]
            detail = self.member_doc(decl, overloads[0])
            anchor = slug(name)
            toc.append((anchor, name))
            content += f'<section class="member-detail" id="{anchor}"><h2><code>{escape(decl.name)}::{escape(name)}</code><a class="anchor-link" href="#{anchor}" aria-label="이 멤버 링크">#</a></h2><p>{self.rich(detail["summary"])}</p>' + self.code("\n".join(m.syntax for m in overloads))
            params = detail.get("params", {})
            if params:
                content += '<h3>매개변수</h3><dl class="parameters">' + "".join(f'<dt><code>{escape(p)}</code></dt><dd>{self.rich(desc)}</dd>' for p, desc in params.items()) + '</dl>'
            if detail.get("returns"):
                content += '<h3>반환 값</h3><p>' + self.rich(detail["returns"]) + '</p>'
            if detail.get("remarks"):
                content += '<h3>설명</h3>' + self.paragraphs(detail["remarks"])
            content += f'<a class="source-link" href="{self.source_link(decl.header, overloads[0].line)}">헤더에서 선언 보기 ↗</a></section>'
        related = doc.get("related", [])
        if related:
            toc.append(("see-also", "참고 항목"))
            content += '<section id="see-also"><h2>참고 항목</h2><div class="related-links">' + "".join(self.link(name) for name in related) + '</div></section>'
        self.page(self.url(key), decl.name + " " + KINDS[decl.kind], self.summary(decl), content, toc, KINDS[decl.kind],
                  f'<span>{KINDS[decl.kind]}</span><span>dy::RHI</span><a href="{self.source_link(decl.header, decl.line)}">RHI/{decl.header}:{decl.line}</a>')

    def index_pages(self):
        counts = Counter(d.kind for d in self.symbols.values())
        content = '<div class="overview-actions"><a class="primary-button" href="getting-started.html">시작하기 <span>→</span></a><a class="secondary-button" href="api-index.html">전체 API 찾아보기</a></div>'
        content += '<div class="stats-strip">' + "".join(f'<div><strong>{number}</strong><span>{label}</span></div>' for number, label in [(len(self.sources), "공개 헤더"), (counts["class"], "클래스"), (counts["struct"], "구조체"), (counts["enum"], "열거형")]) + '</div>'
        content += '<section id="overview"><h2>RHI로 그래픽스 작업 제어하기</h2><p>디바이스 생성부터 명령 기록, 리소스 바인딩, 프레임 제출까지. <code>dy::RHI</code>는 렌더링에 필요한 동작을 C++ 인터페이스로 제공합니다. 애플리케이션이 리소스 수명과 상태 전이를 직접 지정합니다.</p><div class="notice"><strong>현재 문서의 기준</strong><p><code>src/Public/RHI</code>에 선언된 API를 문서화합니다. 구문과 기본값은 공개 헤더에서 추출하며, 사용 규칙은 해당 선언과 저장소 구현을 바탕으로 설명합니다. 예제의 실제 실행에는 선택한 백엔드와 창 시스템의 빌드 구성이 필요합니다.</p></div></section>'
        content += '<section id="browse"><h2>기능별 API 참조</h2><div class="category-grid">'
        introductions = [
            ("01", "디바이스를 만들고 명령을 기록·제출합니다.", ["IDevice", "ICommandList", "SwapchainDesc"]),
            ("02", "버퍼와 텍스처의 생성 정보와 소유권을 정의합니다.", ["BufferDesc", "TextureDesc", "ResourceScope"]),
            ("03", "셰이더 바이너리, 정점 입력, 고정 기능 상태를 구성합니다.", ["ShaderDesc", "GraphicsPipelineDesc"]),
            ("04", "셰이더가 접근할 리소스와 정적 샘플러를 연결합니다.", ["ResourceBinding", "ResourceSetDesc"]),
            ("05", "첨부 이미지, 리소스 상태, 배리어를 명시합니다.", ["RenderingDesc", "ResourceBarrierDesc", "Format"]),
            ("06", "패스 간 읽기·쓰기 의존성을 정리합니다.", ["RenderGraph", "RenderGraphPass"]),
        ]
        for (_, title, _), (number, intro, names) in zip(GROUPS, introductions):
            content += f'<article class="category-card"><span class="category-number">{number}</span><h3>{title}</h3><p>{intro}</p><div>' + "".join(self.link(name) for name in names) + '</div></article>'
        content += '</div></section><section id="frame"><h2>한 프레임의 흐름</h2><p>렌더 타깃의 상태를 전환하고, 명령을 닫은 뒤 디바이스에 제출합니다.</p><ol class="frame-flow">'
        for step, desc in [("BeginFrame", "프레임 시작"), ("AcquireCommandList", "명령 목록 획득"), ("BeginRendering", "렌더링 기록"), ("Close", "기록 종료"), ("Submit", "명령 제출"), ("Present", "화면 표시")]:
            owner = "ICommandList" if step in ("BeginRendering", "Close") else "IDevice"
            content += f'<li><span>{desc}</span><a href="{self.url(owner)}#{slug(step)}"><code>{step}</code></a></li>'
        content += '</ol><p>렌더링 구간은 <code>EndRendering()</code>으로 끝내고, 백 버퍼를 <code>Present</code> 상태로 전환합니다. <a href="getting-started.html#frame">전체 프레임 예제 보기 →</a></p></section>'
        content += '<section id="essentials"><h2>알아둘 규칙</h2>' + self.table(["주제", "규칙"], [
            [self.link("ResourceScope"), "디바이스가 더 오래 살아 있어야 합니다. 등록한 리소스는 종류별 순서로 해제됩니다."],
            [self.link("IDevice", "Submit"), "디바이스 소유의 닫힌 명령 목록은 제출 성공 여부와 무관하게 소비됩니다."],
            [self.link("TextureHandle"), "백 버퍼는 스왑체인 소유입니다. 직접 파괴하거나 ResourceScope에 등록하지 않습니다."],
            [self.link("RenderGraph"), "현재 구현은 실행 순서를 정렬합니다. 필요한 리소스 배리어는 호출자가 기록합니다."],
        ]) + '</section>'
        self.page("index.html", "RHI API 참조", "dy_engine의 Render Hardware Interface를 위한 C++ 레퍼런스입니다. 공개 API의 구문, 기본값, 사용 규칙과 예제를 한곳에서 확인하세요.", content, [("overview", "RHI 개요"), ("browse", "기능별 API 참조"), ("frame", "한 프레임의 흐름"), ("essentials", "알아둘 규칙")], meta='<span>C++17</span><span>네임스페이스 dy::RHI</span><span>한국어</span>')

        content = '<div class="index-filter"><label for="api-filter">API 목록 필터</label><input id="api-filter" type="search" placeholder="이름 또는 설명으로 필터…" autocomplete="off"><p id="filter-status" role="status"></p></div>'
        toc = []
        for kind, anchor in [("class", "classes"), ("struct", "structures"), ("enum", "enumerations"), ("alias", "aliases"), ("function", "functions")]:
            toc.append((anchor, KINDS[kind]))
            rows = [[self.link(key), f'<a href="{self.source_link(d.header)}">{escape(d.header)}</a>', self.rich(self.summary(d))] for key, d in sorted(self.symbols.items()) if d.kind == kind]
            content += f'<section class="index-section" id="{anchor}"><h2>{KINDS[kind]}</h2>{self.table(["API", "헤더", "설명"], rows)}</section>'
        self.page("api-index.html", "전체 API 찾아보기", f"공개 헤더에서 추출한 {len(self.symbols)}개 API 항목입니다. 클래스, 구조체, 열거형, 형식 별칭과 함수를 찾아보세요.", content, toc, "API 목록")

    def header_pages(self):
        rows = []
        for header, source in self.sources.items():
            filename = f'header-{Path(header).stem.lower()}.html'
            symbols = [(key, decl) for key, decl in self.symbols.items() if decl.header == header]
            rows.append([f'<a href="{filename}"><code>RHI/{header}</code></a>', str(len(symbols)), " · ".join(self.link(key) for key, d in symbols if d.kind == "class") or "형식과 선언"])
            content = '<section id="include"><h2>포함 구문</h2>' + self.code(f'#include <RHI/{header}>') + '</section>'
            content += '<section id="declarations"><h2>선언</h2>' + self.table(["이름", "종류", "설명"], [[self.link(key), KINDS[d.kind], self.rich(self.summary(d))] for key, d in symbols]) + '</section>'
            content += '<section id="source"><h2>헤더 소스</h2><p>현재 작업 트리의 공개 헤더에서 생성한 사본입니다.</p><div class="source-code"><pre><code>' + "\n".join(f'<span class="source-line" id="L{i}"><a href="#L{i}" aria-label="{i}행">{i}</a>{escape(line.expandtabs(4))}</span>' for i, line in enumerate(source.splitlines(), 1)) + '</code></pre></div></section>'
            self.page(filename, f"<RHI/{header}>", f"{header}에 정의된 공개 API와 원본 선언을 확인합니다.", content, [("include", "포함 구문"), ("declarations", "선언"), ("source", "헤더 소스")], "헤더")
        self.page("headers.html", "헤더 파일 참조", "RHI API의 공개 헤더 목록입니다. 헤더별 선언과 행 번호가 있는 소스를 확인할 수 있습니다.", '<section id="headers"><h2>공개 헤더</h2>' + self.table(["헤더", "API 항목", "주요 클래스"], rows) + '</section>', [("headers", "공개 헤더")], "헤더")

    def guide_page(self):
        example = (HERE / "examples/clear-frame.cpp").read_text(encoding="utf-8")
        content = '<section id="setup"><h2>1. 공개 헤더 포함하기</h2><p>프로젝트의 include 경로에 <code>src/Public</code>을 추가하고 C++17 이상을 사용합니다. 같은 이름의 기존 내부 헤더가 <code>src/RHI</code>에 있으므로 공개 API를 사용할 때는 <code>src/Public</code>을 우선 검색하도록 설정합니다.</p>' + self.code('#include <RHI/IDevice.h>\n#include <RHI/ICommandList.h>\n#include <RHI/Rendering.h>\n\nusing namespace dy::RHI;') + '<div class="notice"><strong>예제 확인 범위</strong><p>다음 코드는 공개 헤더에 대해 C++17 문법을 검사한 사용 예제입니다. 실제 실행에는 창 시스템과 선택한 네이티브 백엔드를 연결해야 합니다. Null은 명령 검증용이며 실제 화면 렌더링을 제공하지 않습니다. 빌드 설정은 저장소의 <code>examples/README.md</code>를 참고하세요.</p></div></section>'
        content += '<section id="device"><h2>2. 디바이스와 스왑체인 생성하기</h2><p><code>Platform::Window</code>의 핸들을 <code>IDevice::Create</code>에 전달합니다. 스왑체인 포맷과 표시 모드는 <code>SwapchainDesc</code>에서 지정합니다. 디바이스는 리소스보다 오래 유지하세요.</p>' + self.code('std::unique_ptr<IDevice> device(IDevice::Create(window.GetHandle()));\nif (!device) throw std::runtime_error("Device creation failed.");\n\nSwapchainDesc swapchain;\nswapchain.format = Format::B8G8R8A8_UNORM;\nswapchain.minimumImageCount = 2;\nswapchain.presentMode = PresentMode::Fifo;\nif (!device->CreateSwapchain(swapchain))\n    throw std::runtime_error("Swapchain creation failed.");') + '</section>'
        content += '<section id="frame"><h2>3. 프레임을 지우고 표시하기</h2><p>백 버퍼를 렌더 타깃으로 전환한 후 지정한 색으로 지웁니다. 렌더링을 종료하고 표시 상태로 되돌린 다음, 닫힌 명령 목록을 제출합니다. 셰이더나 파이프라인 없이 프레임 수명 주기를 확인하는 예제입니다.</p><a class="source-link" href="examples/clear-frame.cpp" download>clear-frame.cpp 다운로드 ↓</a>' + self.code(example) + '</section>'
        content += '<section id="lifetime"><h2>4. 리소스 수명 관리하기</h2>' + self.paragraphs([
            '`ResourceScope`에는 직접 생성한 리소스만 한 번씩 등록합니다. 디바이스는 scope보다 오래 살아 있어야 하고, 기록한 명령은 리소스를 해제하기 전에 제출하거나 폐기해야 합니다.',
            '`ResourceScope`는 ResourceSet → Pipeline → Shader → Texture → Buffer 순서로 해제하며 각 종류 안에서는 등록의 역순을 따릅니다. 업로드, 배리어, 명령 제출은 호출자가 처리합니다.',
            '`IDevice::GetBackBuffer`가 반환한 텍스처는 스왑체인 소유이므로 DestroyTexture 또는 ResourceScope::Keep에 전달하지 않습니다.',
        ]) + self.code('#include <RHI/Buffer.h>\n#include <RHI/ResourceScope.h>\n\nvoid CreateOwnedBuffer(IDevice& device)\n{\n    ResourceScope resources(device);\n    BufferDesc desc;\n    desc.size = 3 * 3 * sizeof(float);\n    desc.stride = 3 * sizeof(float);\n    desc.usage = BufferUsage::Vertex;\n    desc.initialState = ResourceState::CopyDestination;\n    const BufferHandle vertices = resources.Keep(device.CreateBuffer(desc));\n    (void)vertices;\n    // scope 종료 시 해제됩니다. 생성만으로 데이터가 업로드되지는 않습니다.\n}') + '</section>'
        content += '<section id="next"><h2>다음 단계</h2><div class="related-links">' + "".join(self.link(k) for k in ["IDevice", "ICommandList", "GraphicsPipelineDesc", "ResourceSetDesc", "RenderGraph"]) + '</div><p>더 큰 예제는 저장소의 <code>examples/RHI/01_Primitives</code>부터 <code>09_Text</code>까지 참고하세요.</p></section>'
        self.page("getting-started.html", "RHI 시작하기", "디바이스를 생성하고, 백 버퍼를 지운 뒤 화면에 표시하는 과정을 따라가 봅니다.", content, [("setup", "공개 헤더 포함하기"), ("device", "디바이스와 스왑체인"), ("frame", "프레임 기록과 제출"), ("lifetime", "리소스 수명"), ("next", "다음 단계")], "시작하기")

    def build(self):
        self.index_pages()
        self.header_pages()
        self.guide_page()
        search = []
        for key, decl in self.symbols.items():
            self.symbol_page(key, decl)
            search.append({"title": key, "kind": KINDS[decl.kind], "text": self.summary(decl), "url": self.url(key), "header": decl.header})
            for name in dict.fromkeys(m.name for m in decl.members):
                member = next(m for m in decl.members if m.name == name)
                search.append({"title": f"{decl.name}::{name}", "kind": "멤버", "text": self.member_doc(decl, member)["summary"], "url": self.url(key) + "#" + slug(name), "header": decl.header})
        self.pages["assets/search-index.js"] = "// Generated by docs/rhi/generate.py.\nwindow.RHI_SEARCH = " + json.dumps(search, ensure_ascii=False, separators=(",", ":")) + ";\n"
        self.pages["manifest.json"] = json.dumps({
            "generator": "docs/rhi/generate.py", "source_root": "src/Public/RHI",
            "headers": {name: hashlib.sha256(source.encode()).hexdigest() for name, source in self.sources.items()},
            "symbols": len(self.symbols), "search_entries": len(search),
            "pages": sorted(name for name in self.pages if name.endswith(".html")),
        }, ensure_ascii=False, indent=2) + "\n"
        return self.pages


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Fail if generated documents differ from the current headers or content")
    args = parser.parse_args()
    reference = Reference()
    pages = reference.build()
    stale = [path for path in HERE.glob("*.html") if MARKER in path.read_text(encoding="utf-8") and path.name not in pages]
    changed = [name for name, content in pages.items() if not (HERE / name).exists() or (HERE / name).read_text(encoding="utf-8") != content]
    if args.check:
        if stale or changed:
            print("RHI documentation is stale. Run: python3 docs/rhi/generate.py", file=sys.stderr)
            for name in changed + [p.name for p in stale]:
                print(f"  {name}", file=sys.stderr)
            return 1
    else:
        for name in changed:
            path = HERE / name
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(pages[name], encoding="utf-8")
        for path in stale:
            path.unlink()
    print(f"{'Verified' if args.check else 'Generated'} {len(reference.symbols)} API entries from {len(reference.sources)} headers; {sum(n.endswith('.html') for n in pages)} HTML pages.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
